### ISSUE TITLE
Open source Microsoft.SqlServer.TransactSql.ScriptDom

### ISSUE THREAD

**Issue by clement911** [microsoft/DacFx#101]
Can you please please open source Microsoft.SqlServer.TransactSql.ScriptDom.dll?

The parser is useful, but there are still a lot of gaps that we'd like to contribute to.

This doesn't strike me as a sensitive library and we can already 'see it' in ILSpy or any other decompiler.

Could someone please raise it to the relevant people at Microsoft?

**Comment by clement911** [comment]
Pretty please anyone from Microsoft could you please help 🙏?

**Comment by dzsquared** [comment]
ScriptDom is still on the list of components to open source and is part of the DacFx project, so this is the correct location for this discussion.

**Comment by clement911** [comment]
Thank you @dzsquared for your update.
To clarify, are you saying that it is on the roadmap to open source it? I understand this might not be a priority but is there a rough ETA?

**Comment by clement911** [comment]
I'd like to raise my hand and offer any help that might be useful to get the script Dom library open source.

**Comment by clement911** [comment]
🙏🙏🙏

**Comment by clement911** [comment]
So it's been 2 and half years and no movement at all on this.
What's blocking this from moving forward?
The parser has lots of bugs and we have no way of fixing them...

**Comment by clement911** [comment]
😪

**Comment by ADARSOFT** [comment]
I also join the comments of Mr. @clement911 and hope that Microsoft will initiate this open-source project, which will definitely lead to an improvement in the quality of writing tsql code for the entire community.

**Comment by llali** [comment]
ScriptDom is now open-source https://github.com/microsoft/SqlScriptDom

**Comment by clement911** [comment]
OMG thank you!!! 💙💙💙
