### ISSUE TITLE
GENERATE_SERIES syntax is not recognized

### ISSUE THREAD

**Issue by arvindshmicrosoft** [microsoft/DacFx#105]
- SqlPackage or DacFx Version: 160.6164.0-preview
- .NET Framework (Windows-only) or .NET Core: Framework 4.8
- Environment (local platform and source/target platforms): Windows AnyCPU

**Steps to Reproduce:**
```sql
SELECT value FROM GENERATE_SERIES(START = 1, STOP = 5);
SELECT value FROM GENERATE_SERIES(START = 1, STOP = 32, STEP = 7);
SELECT value FROM GENERATE_SERIES(START = 1, STOP = 5) ORDER BY value;
```
Parsing this using TSqlParser160 yields:
```
46010 @ 1,41: Incorrect syntax near =.
46010 @ 2,41: Incorrect syntax near =.
46010 @ 3,41: Incorrect syntax near =.
```
**Did this occur in prior versions?  If not - which version(s) did it work in?**
No, this is not a regression as this is new functionality in SQL Server 2022.

**Comment by dzsquared** [comment]
This is on the backlog now for future completion - thanks!

**Comment by zijchen** [comment]
To clarify, the sample T-SQL is incorrect syntax, the correct syntax is
```tsql
SELECT value FROM GENERATE_SERIES(1, 5);
SELECT value FROM GENERATE_SERIES(1, 32, 7);
SELECT value FROM GENERATE_SERIES(1, 5) ORDER BY value;
```
This syntax actually parses correctly with TSql160Parser, but we are working to support this in the other parts of DacFx such as model building, model compare, etc.
