### ISSUE TITLE
Not able to use Contained user and login after restoring .BACPAC to Azure SQL DB

### ISSUE THREAD

**Issue by yobelwal** [microsoft/DacFx#107]
- SqlPackage or DacFx Version:
- .NET Framework (Windows-only) or .NET Core:
- Environment (local platform and source/target platforms):

**Steps to Reproduce:**

1. Export Azure SQL Database ( which have contained user/ login)
2. Import Azure SQL Database.
3. Try to connect to the database from the available contained user. It will fail.
4.  Try changing password ( try to use the same password )
ALTER USER [USERNAME] WITH PASSWORD=[PASSWORD]
5. Try to connect again. This will be success.

Ask- Is this an expected behaviour?
**Did this occur in prior versions?  If not - which version(s) did it work in?**

(DacFx/SqlPackage/SSMS/Azure Data Studio)

**Comment by yobelwal** [comment]
Thanks for the confirmation @llali

**Comment by dzsquared** [comment]
Added to docs: https://docs.microsoft.com/en-us/sql/tools/sqlpackage/sqlpackage?view=sql-server-ver15#sqlpackage-and-database-users

**Comment by yobelwal** [comment]
Thanks @dzsquared
