### ISSUE TITLE
Refresh official docs for ScriptDom from DacFx 160

### ISSUE THREAD

**Issue by arvindshmicrosoft** [microsoft/DacFx#109]
- SqlPackage or DacFx Version: DacFx 160
- .NET Framework (Windows-only) or .NET Core: All
- Environment (local platform and source/target platforms): All

**Steps to Reproduce:**

Visiting the [doc page](https://docs.microsoft.com/en-us/dotnet/api/microsoft.sqlserver.transactsql.scriptdom.tsqlparser) only shows entries for DacFx 150 and DacFx 140. Since DacFx 160 has been out for a while now, the documentation should be refreshed.

**Did this occur in prior versions?  If not - which version(s) did it work in?**
N/A

**Comment by dzsquared** [comment]
DacFx 160 dotnet API docs are now updated - https://docs.microsoft.com/en-us/dotnet/api/Microsoft.SqlServer.Dac?view=sql-dacfx-160 (incl scriptdom)
