### ISSUE TITLE
Microsoft.Build.Sql doesn't work on Linux

### ISSUE THREAD

**Issue by zwcloud** [microsoft/DacFx#122]
- SqlPackage or DacFx Version:  not using DacFx, just [`Microsoft.Build.Sql` as described in the docs](https://github.com/microsoft/DacFx/tree/main/src/Microsoft.Build.Sql#using-this-sdk)
- .NET Framework (Windows-only) or .NET Core:  
![image](https://user-images.githubusercontent.com/6965758/181230330-13b6f1c9-cc65-4877-a6fe-07a92f98a41c.png)
- Environment (local platform and source/target platforms): Ubuntu 20.04

**Steps to Reproduce:**

```
git clone https://github.com/zwcloud/Kandu
git checkout fixSqlProj
dotnet build
```
See error:
```
root@localhost:~/kandu# dotnet build
Microsoft (R) Build Engine version 17.2.0+41abc5629 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

/root/kandu/Sql/Sql.sqlproj : warning NU1503: Skipping restore for project '/root/kandu/Sql/Sql.sqlproj'. The project file may be invalid or missing targets required for restore. [/root/kandu/Kandu.sln]
  Determining projects to restore...
  All projects are up-to-date for restore.
  Query -> /root/kandu/Query/bin/Debug/net5.0/Query.dll
  Core -> /root/kandu/Core/bin/Debug/net5.0/Kandu.Core.dll
  Kandu -> /root/kandu/App/bin/Debug/net6.0/Kandu.dll
/root/.nuget/packages/microsoft.build.sql/0.1.3-preview/sdk/Sdk.targets(12,3): error MSB4019: The imported project "/usr/share/dotnet/sdk/6.0.302/Microsoft/VisualStudio/v16.0/SSDT/Microsoft.Data.Tools.Schema.SqlTasks.targets" was not found. Confirm that the expression in the Import declaration "/usr/share/dotnet/sdk/6.0.302//Microsoft/VisualStudio/v16.0/SSDT/Microsoft.Data.Tools.Schema.SqlTasks.targets" is correct, and that the file exists on disk. [/root/kandu/Sql/Sql.sqlproj]
```
https://github.com/microsoft/DacFx/blob/d39dcf99b6032cfb3723eb382ea3cb4f54ab1f9d/src/Microsoft.Build.Sql/sdk/Sdk.targets#L12 This line still references a file from Visual Studio: `$(MSBuildExtensionsPath)\Microsoft\VisualStudio\v$(VisualStudioVersion)\SSDT\Microsoft.Data.Tools.Schema.SqlTasks.targets`

**Did this occur in prior versions?  If not - which version(s) did it work in?**
No. But I have tried to run `dotnet build` on windows and it works:
![image](https://user-images.githubusercontent.com/6965758/181229946-58067718-26a1-4d3a-8bef-bb29e63209d9.png)
(DacFx/SqlPackage/SSMS/Azure Data Studio)

**Comment by ErikEJ** [comment]
Did you read the [readme](https://github.com/microsoft/DacFx/blob/main/src/Microsoft.Build.Sql/README.md#resolving-build-errorswarnings) ?

**Comment by zwcloud** [comment]
> Did you read the [readme](https://github.com/microsoft/DacFx/blob/main/src/Microsoft.Build.Sql/README.md#resolving-build-errorswarnings) ?

As described, this line is in this repo, not mine.

**Comment by ErikEJ** [comment]
Did you build with:

    dotnet build /p:NetCoreBuild=true

**Comment by zwcloud** [comment]
And what to do next:
https://www.programmingwithwolfgang.com/deploy-dacpac-linux-azure-devops/

I didn't found documentation on how to do this without azure devops but do it manually on a linux VPS without docker. @ErikEJ Do you know any?

**Comment by ErikEJ** [comment]
Basically you need to run the "sqlpackage" tool with the Publish action.
