### ISSUE TITLE
sqlpackage.exe DropObjectsNotInSource missing exclude for Schema

### ISSUE THREAD

**Issue by czb182** [microsoft/DacFx#129]
sqlpackage.exe doesnt have a way to specify to ignore schema's. If I pass /p:DropObjectsNotInSource=True it wants to drop all schemas outside my dacpac when publishing. For example it generates this if I am deploying a dacpac that does not have "CREATE SCHEMA [abc]]" defined

PRINT N'Dropping SqlSchema [abc]...';
DROP SCHEMA [abc];
GO

There is no type I can pass to p:DoNotDropObjectTypes to have it not drop these.

If list of types can not be adjusted to have schema, maybe an additional flag can be added like "DropSchemasNotInSource=(BOOLEAN)". I have checked Microsoft.SqlServer.Dac.ObjectType and there is no value for Schema currently.

**Comment by dzsquared** [comment]
duplicate to #24
