### ISSUE TITLE
restrict sqlpackage to specified schema

### ISSUE THREAD

**Issue by czb182** [microsoft/DacFx#131]
We use database schema's to isolate our various microservices data. for example [abc],[def],[hig], etc.  We build dacpacs for all of our microservices, each one for a given schema.  Ideally we shoould be to specify flag like "/p:TargetSchema=def" to give sqlpackage ignore other schemas.  This would be useful if we turned on "DropObjectsNotInSource" so that it wouldn't want to drop all the other schemas we use.

**Comment by dzsquared** [comment]
duplicate to #24
