### ISSUE TITLE
ScriptDom parser for Sql Server 2022 fails to parse IGNORE NULLS clause

### ISSUE THREAD

**Issue by clement911** [microsoft/DacFx#133]
- SqlPackage or DacFx Version: 160.6266.0-preview
- .NET Framework (Windows-only) or .NET Core: .NET 6.0 (Core)
- Environment (local platform and source/target platforms): N/A

**Steps to Reproduce:**

1. Create a new C# Console Project
2. Add latest Nuget package for Microsoft.SqlServer.DacFx (160.6266.0-preview)
3. Run code below

```csharp
using Microsoft.SqlServer.TransactSql.ScriptDom;

var parser = new TSql160Parser(true); //sql server 2022 parser
IList<ParseError> errors;

parser.ParseExpression(new StringReader("LAST_VALUE(Measure) OVER()"), out errors);
//no parsing errors

parser.ParseExpression(new StringReader("LAST_VALUE(Measure) IGNORE NULLS OVER()"), out errors);
//parsing error! "Incorrect syntax near IGNORE." This should parse succesfully

Console.ReadLine();
```

**Did this occur in prior versions?  If not - which version(s) did it work in?**
Not applicable because the Sql Server 2022 parser (TSQL 160 didn't exist in prior versions).

Documentation about the support for IGNORE NULLS / RESPECT NULLS in Sql Server 2022 is here: https://docs.microsoft.com/en-us/sql/t-sql/functions/last-value-transact-sql?view=sql-server-ver16#-ignore-nulls--respect-nulls-

**Comment by dzsquared** [comment]
similar bucket to #105

**Comment by clement911** [comment]
@dzsquared any updates on open sourcing the ScriptDom lib?
This kind of bug really gets us stuck and we cannot implement our DB tool for sql azure and sql server 2022 until a fix is released, because scripts that are valid don't parse.
If we could contribute, we could send a PR to fix these issues.

**Comment by clement911** [comment]
Please open up the code so that we can contribute and fix bugs.

**Comment by zijchen** [comment]
@clement911 - ScriptDom is one of the projects we plan to open-source first. In the meantime, support for this syntax should be in our [latest 160.6324.0-preview release](https://www.nuget.org/packages/Microsoft.SqlServer.DacFx/160.6324.0-preview). Please give it a try!

**Comment by clement911** [comment]
@zijchen I can confirm that parsing of the expression above now works on version 161.6337.0-preview.

However, I find the object model weird. Why is the  `IgnoreRespectNulls` property a list of Identifiers? 

```csharp
public IList<Identifier> IgnoreRespectNulls { get; }
```

We would expect a proper Fragment class IgnoreRespectNullsClause or maybe a simple a simple enum

Maybe something along the following lines?
```csharp
public enum IgnoreRespectNulls
{
  NotSpecified,
  IgnoreNulls,
  RespectNulls
}
```

p.s.: I also tested a long standing bug causing the parser to fail to parse nested IIF calls. I'm pleased to see this appears to be fixed!

**Comment by zijchen** [comment]
@namangupta211 FYI, maybe we can keep this issue open as an enhancement to implement the IgnoreRespectNulls as its own clause instead of a list of identifiers

**Comment by clement911** [comment]
@llali I see that you have closed. Was the enhancement mentioned above implemented?

**Comment by llali** [comment]
@namangupta211 do you want to create a separate task for the enhancement mentioned above? The bug was originally created for the parser bug so that's why I closed it since it's fixed

**Comment by clement911** [comment]
@namangupta211 ?

**Comment by llali** [comment]
@clement911 I added the feature request here: https://github.com/microsoft/DacFx/issues/181 please add any missing details. Thanks

**Comment by clement911** [comment]
Thanks @llali 

@zijchen any eta on open sourcing?

**Comment by clement911** [comment]
I see a new [stable version of the package was released](https://www.nuget.org/packages/Microsoft.SqlServer.DacFx/161.6374.0) yet this is still not fixed
