### ISSUE TITLE
SqlPackage.exe fails to recreate Full Text Index on the target database

### ISSUE THREAD

**Issue by vidhyasagarreddy** [microsoft/DacFx#137]
I have a Full-Text Index as part of my SQL Project; when I run SqlPackage.exe on Azure Pipelines/local, it fails with following log:

Pre deployment script execution started..
Pre deployment script execution finished.
Dropping Full-text Index Full-text Index on [dbo].[XXXXXX]...
Altering Table [dbo].[XXXXXX]...
Creating Full-text Index Full-text Index on [dbo].[XXXXXX]...
Rebinding full-text index on [dbo].[XXXXXX]...
(98,1): SQL72014: .Net SqlClient Data Provider: Msg 7672, Level 16, State 1, Line 1 A full-text index cannot be created on the table or indexed view because duplicate column 'YYYYYY' is specified.
(98,0): SQL72045: Script execution error.  The executed script:
ALTER FULLTEXT INDEX ON [dbo].[XXXXXX] ADD ([YYYYYY] LANGUAGE 1033);

An error occurred while the batch was being executed.

**Comment by Benjin** [comment]
Hi @vidhyasagarreddy,

Can you provide a pair of sample dacpacs (both Source and Target) that reproduce this issue?  If you'd prefer, you can email them to ssdteng@microsoft.com, and include a link to this GitHub issue.  Thanks!
