### ISSUE TITLE
/p:BackupDatabaseBeforeChanges=true in sqlpackage.exe (action publish), not working for azure SQL database

### ISSUE THREAD

**Issue by abhi421** [microsoft/DacFx#138]
- SqlPackage or DacFx Version:
- .NET Framework (Windows-only) or .NET Core:
- Environment (local platform and source/target platforms):

**Steps to Reproduce:**
I m getting error while publishing the profile  when I add BackupDatabaseBeforeChanges =true target Db is azure SQL database

//error
SQL72014: .Net SqlClient Data Provider: Msg 40515, Level 15, State 1, Line 16 Reference to database and/or server name in 'master.dbo.xp_instance_regread' is not supported in this version of SQL Server.
(39,0): SQL72045: Script execution error. The executed script:
IF (DB_ID(N'$(DatabaseName)') IS NOT NULL)
BEGIN
DECLARE @rc AS INT, @fn AS NVARCHAR (4000), @dir AS NVARCHAR (4000);
EXECUTE @rc = [master].[dbo].[xp_instance_regread] N'HKEY_LOCAL_MACHINE', N'Software\Microsoft\MSSQLServer\MSSQLServer', N'BackupDirectory', @dir OUTPUT, 'no_output';
IF (@rc = 0)
SELECT @dir = @dir + N'';
IF (@dir IS NULL)
BEGIN
EXECUTE @rc = [master].[dbo].[xp_instance_regread] N'HKEY_LOCAL_MACHINE', N'Software\Microsoft\MSSQLServer\MSSQLServer', N'DefaultData', @dir OUTPUT, 'no_output';
IF (@rc = 0)
SELECT @dir = @dir + N'';
END
IF (@dir IS NULL)
BEGIN
EXECUTE @rc = [master].[dbo].[xp_instance_regread] N'HKEY_LOCAL_MACHINE', N'Software\Microsoft\MSSQLServer\Setup', N'SQLDataRoot', @dir OUTPUT, 'no_output';
IF (@rc = 0)
SELECT @dir = @dir + N'\Backup';
END
IF
An error occurred while the batch was being executed.

(DacFx/SqlPackage/SSMS/Azure Data Studio)

**Comment by Benjin** [comment]
Hi @abhi421, that option is not available for Azure SQL Databases, per the [documentation for SqlPackage](https://docs.microsoft.com/en-us/sql/tools/sqlpackage/sqlpackage-publish?view=sql-server-ver15).  You can configure automated backups for your database through the Azure portal, if you'd like.
