### ISSUE TITLE
Support for greatest() and least()

### ISSUE THREAD

**Issue by dzsquared** [microsoft/DacFx#142]
Support for SQL2022 syntax for greatest and least:
- https://docs.microsoft.com/en-us/sql/t-sql/functions/logical-functions-greatest-transact-sql?view=sql-server-ver16
- https://docs.microsoft.com/en-us/sql/t-sql/functions/logical-functions-least-transact-sql?view=sql-server-ver16

**Comment by zijchen** [comment]
Supported by default
