### ISSUE TITLE
Don't Require Gatekeeper Subsystem (spctl) to be Disabled when running SqlPackage on Mac 

### ISSUE THREAD

**Issue by chlafreniere** [microsoft/DacFx#145]
- SqlPackage or DacFx Version: All SqlPackage versions on MacOS
- .NET Framework (Windows-only) or .NET Core: Core
- Environment (local platform and source/target platforms): MacOS

Currently, it is required to run the following commands when interacting with SqlPackage on MacOS ([docs](https://learn.microsoft.com/en-us/sql/tools/sqlpackage/sqlpackage-download?view=sql-server-ver16#macos-net-core)):

``` bash
sudo spctl --master-disable
[SqlPackage commands]
sudo spctl --master-disable
```
Expected:
No gatekeeper modifications need to be made to execute SqlPackage on MacOS

**Comment by dzsquared** [comment]
Not planned as installing sqlpackage via dotnet tool does not require changes to gatekeeper

https://learn.microsoft.com/en-us/sql/tools/sqlpackage/sqlpackage-download?view=sql-server-ver16#installation-cross-platform

```bash
dotnet tool install -g microsoft.sqlpackage
```
