### ISSUE TITLE
Moving from Microsoft.SqlServer.DacFx.x64 to the Microsoft.SqlServer.DacFx

### ISSUE THREAD

**Issue by jaskiniowiec135** [microsoft/DacFx#152]
- SqlPackage or DacFx Version: 160.6296.0
- .NET Framework (Windows-only) or .NET Core: .Net 6.0
- Environment (local platform and source/target platforms): Windows

**Steps to Reproduce:**

1. Install the newest official package (not prerelease)
2. Try to call SqlHierarchyId.Parse()

After moving from the legacy package which is Microsoft.SqlServer.DacFx.x64 I'm not able to call some methods from SqlHierarchyId class. However, when I select the prerelease version of the package, all of that methods are available, because there is a lack of this dll and it is taken from Microsoft.SqlServer.Types installed package. As far as I investigated in the official packages Microsoft.SqlServer.Types.dll library is really small for net6.0 and netstandard2.1 frameworks, which indicates that those methods are not prepared, while net462 contains all the needed methods. Moreover, in the newest prerelease version, which is 161.6304.0-preview, this dll is not present at all for all frameworks. Is it on purpose that this dll is reduced in the official version and there is none in the prerelease version? Am I able to manually force using the Microsoft.SqlServer.Types.dll file by another package like Microsoft.SqlServer.DacFx, while this dll is used in this package? Or at least am I able to force an application to use the net462 framework package in .net 6.0 application?

PS.
There is also a strange behavior on SqlHierarchyId, because in one of our classes we are using the following structure for specific field.

        public SqlHierarchyId NodeId => SqlHierarchyId.Parse(Path);

While this structure works fine during the application run, it breaks during the unit tests, even on the legacy package version. I hope that solving the problem with lacking Microsoft.SqlServer.Types.dll also fix problem with unit tests.

(DacFx/SqlPackage/SSMS/Azure Data Studio)

**Comment by SeenaAugusty** [comment]
Hi @jaskiniowiec135, As of now, could you kindly use the pre release version and the GA version with all the needed methods would be released soon. Thank you for your patience. Also, could you please share the details of the error message when the unit tests failed and the details of the unit test.

**Comment by jaskiniowiec135** [comment]
Hi @SeenaAugusty, because of company policy we are not able to use the pre-release version, so for now we have to stick with the legacy package. Using the pre-release version work just fine, but using the newest package (160.6296.0) results in the compilation error says there is no Parse method for SqlHierarchyId class. I tried to use the dotmorten.Microsoft.SqlServer.Types package as a workaround to get rid of the legacy package, because to be honest I only need Microsoft.SqlServer.Types namespace from the whole Microsoft.SqlServer.DacFx package in this particular project, but there is still an error with the unit tests. The error during running the unit tests is raised while getting the NodeId field which I showed above, with the message saying that there is no Parse method, just like the compilation error while using the released version of Microsoft.SqlServer.DacFx package.

**Comment by SeenaAugusty** [comment]
Hey @jaskiniowiec135
Can you try in Microsoft.SqlServer.DacFx Version 161.6374.0 and see if the issue still exists. As it is resolved there, we could close this issue. Thank you very much.

**Comment by jaskiniowiec135** [comment]
Hi @SeenaAugusty,
I have tried the mentioned version and after removing other packages I'm able to proceed with the unit tests. It is all green, so we can close the bug. Thank you!

**Comment by SeenaAugusty** [comment]
Thank you @jaskiniowiec135 for the update.
