### ISSUE TITLE
Surface breaking connection changes due to MDS upgrade

### ISSUE THREAD

**Issue by dzsquared** [microsoft/DacFx#154]
**Is your feature request related to a problem? Please describe.**
In next versions of SqlPackage - the upgrade from MDS3 to MDS5 means that some commands with connection strings that previously worked will suddenly not work against sqlpackage with SqlClient 5.

**Describe the solution you'd like**
Let's surface a link to the breaking change details or specific error messages to guide users through the migration.

**Additional context**
One scenario of biggest concern is the automatically updated pipeline agents that will pick up the new SqlPackage and could result in sudden failures to automated tasks.

**Comment by ErikEJ** [comment]
Could you do an Update to 160 that emits a warning and a link?
