### ISSUE TITLE
Microsoft.Build.Sql - CSC : error cs2012 Cannot open 'foo.dll' because it is being used by another process

### ISSUE THREAD

**Issue by pgodwin** [microsoft/DacFx#159]
When running `dotnet build` more than once, CSC returns cs2012. It looks like `dotnet build` is spawning multiple instances of dotnet for msbuild, but leaving them running after the build completes.

- SqlPackage or DacFx Version: Microsoft.Build.Sql 0.1.3-preview
- .NET Framework (Windows-only) or .NET Core: 6.0.203
- Environment (local platform and source/target platforms): Windows 11 x64

**Steps to Reproduce:**
1. Run `dotnet build /p:NetCoreBuild=true` against a solution containing multiple dependent sqlproj files
2. Run `dotnet build /p:NetCoreBuild=true` against the same solution again - you should get csc CS2012 errors. 
3. Validate a similar issue with `dotnet clean /p:NetCoreBuild=true` note that warnings: `>C:\Program Files\dotnet\sdk\6.0.203\Microsoft.Common.CurrentVersion.targets(5598,5): warning MSB3061: Unable to delete file "obj\debug\foo.dll". Access to the path 'obj\Debug\Foo.dll' is denied. [foo.sqlproj]`
4. Check task manager, note that many `dotnet.exe` processes are running: 
<img width="1256" alt="image" src="https://user-images.githubusercontent.com/1046558/197704383-40b724bc-c352-4aeb-8725-312569fed5bb.png">

5. Run `taskkill /im:dotnet.exe /f` to kill the dotnet proceses
6. Run `dotnet build /p:NetCoreBuild=true` - the build succeeeds

**Did this occur in prior versions?  If not - which version(s) did it work in?**
Unsure

**Comment by DanielTheCoder** [comment]
Run today into the same issue.
Are there any other workarounds know for this?
I want to avoid always killing dotnet.exe processes.

**Comment by zijchen** [comment]
This issue should be fixed with the 0.1.10-preview release. Please reopen this issue if the problem persists.
