### ISSUE TITLE
Provide Mechanism to exclude objects from export when using sqlpackage.exe table data from synapse

### ISSUE THREAD

**Issue by jasonhorner** [microsoft/DacFx#16]
it would be nice to be able to specify a list of objects to include or exclude when exporting the data from synapse via sqlpackage.exe

In some cases I may want to skip a particularly large object. or just extract the data for a single object.

**Comment by abhikum** [comment]
@jasonhorner - you can use /p:TableData in format schema_name.table_identifier to specify the table data whose data needs to be exported. /p:TableData property may be specified multiple times to indicate multiple tables.
Example: /p:TableData=dbo.DimProduct /p:TableData=dbo.DimEmployee
