### ISSUE TITLE
Unable to build in VS - Visual Studio support for Microsoft.Build.Sql

### ISSUE THREAD

**Issue by ErikEJ** [microsoft/DacFx#180]
- SqlPackage or DacFx Version: 161
- .NET Framework (Windows-only) or .NET Core: Windows
- Environment (local platform and source/target platforms):

**Steps to Reproduce:**

1. Attempt to load/build a new sqlproj based on template 0.1.7
2. Load fails
3. adding this enables the build:

```xml
    <TargetDatabaseSet>True</TargetDatabaseSet>
    <TargetFrameworkVersion>v4.8</TargetFrameworkVersion>
    <TargetFrameworkProfile />
    <ProjectGuid>{f1ee546e-2489-4a7b-9d69-7e2849143721}</ProjectGuid>

```

**Comment by Real-JD-UK** [comment]
@ErikEJ can you even build the project in VS?

even with the 4 lines you mentioned, I get 
"Error:  : Your project does not reference ".NETFramework,Version=v4.8" framework. Add a reference to ".NETFramework,Version=v4.8" in the "TargetFrameworks" property of your project file and then re-run NuGet restore."

full project contents:

```
<?xml version="1.0" encoding="utf-8"?>
<Project DefaultTargets="Build">
  <Sdk Name="Microsoft.Build.Sql" Version="0.1.3-preview" />
  <PropertyGroup>
    <Name>My.Database</Name>
    <DSP>Microsoft.Data.Tools.Schema.Sql.SqlAzureV12DatabaseSchemaProvider</DSP>
    <ModelCollation>1033, CI</ModelCollation>
    <TargetDatabaseSet>True</TargetDatabaseSet>
    <TargetFrameworkVersion>v4.8</TargetFrameworkVersion>
    <TargetFrameworkProfile />
    <ProjectGuid>{0e4d9e11-0dd4-4f05-9caa-684d32f16f99}</ProjectGuid>
  </PropertyGroup>
</Project>
```

**Comment by ErikEJ** [comment]
@Real-JD-UK you are not using the latest SDK version

**Comment by ssreerama** [comment]
Hi @ErikEJ , can you be more specific on how you create the project and where you are trying to build it?

I have created a sample SDK style project on Azure Data Studio (1.40.0) and was able to build it in ADS. Are you trying to open the project in the Visual Studio? If so, the SDK style project is supported in VS yet!

With the project I was able to build "dotnet build "path/sampleproj.sqlproj" /p:NetCoreBuild=true", but msbuild is failing with "our project does not reference ".NETFramework,Version=v4.8" framework"! is this what you are referring about?

**Comment by ErikEJ** [comment]
Yes, as the title of the issue states this is about building in VS. Its all fine that you can build in limited cross platform tooling  but the circle is not complete until you can build in VS and get the intellisense and table editing experience.

**Comment by ssreerama** [comment]
I had a typo in my previous comment and edited. We do have a future enhancement for the VS to support SDK style projects and will support that in future.

**Comment by dzsquared** [comment]
Support for Microsoft.Build.Sql sqlprojects is planned for future Visual Studio (SSDT) releases.  Reopening this item until it is shipped

**Comment by CSharpFiasco** [comment]
I had a similar issue, and I was able to resolve this by deleting the obj folder for my project. And so, I set up the project to clean the project and to delete the obj folder before clean. It's still a work in progress, but I landed on the code below to both build in Visual Studio 2022 and via the dotnet cli. The dotnet cli seems to build just fine without deleting the obj folder, but it wasn't deleting the folder, so I just added ContinueOnError="True".

```
<?xml version="1.0" encoding="utf-8"?>
<Project DefaultTargets="Build" ToolsVersion="4.0">
  <Sdk Name="Microsoft.Build.Sql" Version="0.1.7-preview" />
  <PropertyGroup>
    <Name>sample</Name>
    <DSP>Microsoft.Data.Tools.Schema.Sql.Sql160DatabaseSchemaProvider</DSP>
    <ModelCollation>1033, CI</ModelCollation>
    <ProjectGuid>{939b2fc6-e398-4920-a5d4-7b3816c0b3a5}</ProjectGuid>
    <TargetDatabaseSet>True</TargetDatabaseSet>
  </PropertyGroup>
  <ItemGroup>
    <Folder Include="Properties" />
  </ItemGroup>
  <Target Name="CleanOutputPath" BeforeTargets="Clean">
  <!-- Remove obj folder -->
  <RemoveDir Directories="$(BaseIntermediateOutputPath)" Condition="Exists('$(BaseIntermediateOutputPath)')" ContinueOnError="True" />
</Target>
  <Target Name="PreBuildClean" BeforeTargets="Build">
    <Message Text="PreBuildClean - Starting clean"/>
    <CallTarget Targets="Clean" ></CallTarget>
    <Message Text="PreBuildClean - Finished clean" />
  </Target>
</Project>
```

**Comment by jthapa01** [comment]
> @ErikEJ can you even build the project in VS?
> 
> even with the 4 lines you mentioned, I get "Error: : Your project does not reference ".NETFramework,Version=v4.8" framework. Add a reference to ".NETFramework,Version=v4.8" in the "TargetFrameworks" property of your project file and then re-run NuGet restore."
> 
> full project contents:
> 
> ```
> <?xml version="1.0" encoding="utf-8"?>
> <Project DefaultTargets="Build">
>   <Sdk Name="Microsoft.Build.Sql" Version="0.1.3-preview" />
>   <PropertyGroup>
>     <Name>My.Database</Name>
>     <DSP>Microsoft.Data.Tools.Schema.Sql.SqlAzureV12DatabaseSchemaProvider</DSP>
>     <ModelCollation>1033, CI</ModelCollation>
>     <TargetDatabaseSet>True</TargetDatabaseSet>
>     <TargetFrameworkVersion>v4.8</TargetFrameworkVersion>
>     <TargetFrameworkProfile />
>     <ProjectGuid>{0e4d9e11-0dd4-4f05-9caa-684d32f16f99}</ProjectGuid>
>   </PropertyGroup>
> </Project>
> ```

<TargetDatabaseSet>True</TargetDatabaseSet>
what this property does?

**Comment by nholland20** [comment]
For those with Visual Studio issues? Are your files loading properly in Visual Studio? Also, if I have a .sql file in my output directory (as in the one created from a build), it won't load the project. Has anyone seen this issue?

**Comment by Nathalilly** [comment]
When I try to build in visual studio **after** building in AzureDataSudio I get this error:
"Error: : Your project does not reference ".NETFramework,Version=v4.8.1" framework. Add a reference to ".NETFramework,Version=v4.8" in the "TargetFrameworks" property of your project file and then re-run NuGet restore."

If I delete the project.assets.json file from the obj folder then it will build fine.

**Comment by gzinger** [comment]
When will have support for SDK-style projects in Visual Studio? It seems like an easy-to-do feature that would be very useful for may of us, but seems to be delayed for more than a year already.

**Comment by nholland20** [comment]
With the new version, "0.1.15-preview", I can no longer build from the command line if I have the fix that CSharpFiasco posted above to build from Visual Studio. However, if I don't have that fix, I still can't build from Visual Studio.
The error:
`\Microsoft.PackageDependencyResolution.targets(267,5): error NETSDK1004: Assets file '<filepath>\project.assets.json' not found. Run a NuGet package restore to generate this file.`
Running dotnet restore did not work. Only deleting the PreBuild target made it work.

**Comment by RyanThomas73** [comment]
Sharing what my customized .sqproj file ended up being for others who come across this thread while trying to troubleshoot new use of this project sdk:

```xml
<?xml version="1.0" encoding="utf-8"?>
<Project DefaultTargets="Build">
  <Sdk Name="Microsoft.Build.Sql" Version="0.1.15-preview" />
  <PropertyGroup>
    <Name>YourProjectName</Name>
    <DSP>Microsoft.Data.Tools.Schema.Sql.Sql160DatabaseSchemaProvider</DSP>
    <ModelCollation>1033, CI</ModelCollation>
    <ProjectGuid>{your-project-guild}</ProjectGuid>
    <TargetDatabaseSet>True</TargetDatabaseSet>
    <!-- 
      The sdk will target netstandard2.1 automatically when doing a dotnet cli build but we need to target 
      netframework when the msbuild type is full (a.k.a. building from within Visual Studio) until the Visual Studio
      SSDT extension supports the new sql project SDK.
    -->
    <TargetFrameworkVersion Condition="'$(MSBuildRuntimeType)' != 'Core'">v4.8</TargetFrameworkVersion>
    <TargetFrameworkProfile Condition="'$(MSBuildRuntimeType)' != 'Core'" />
  </PropertyGroup>

  <!-- 
    NOTE: The sql project sdk automatically includes a default globbing pattern for sql files but we still need them to be listed 
    explicitly for VisualStudio SSDT to display them

    See: https://github.com/microsoft/DacFx/blob/main/src/Microsoft.Build.Sql/docs/Converting-Existing.md#default-sql-files-included-in-build
    See: https://github.com/microsoft/DacFx/blob/a888164f1e83f0b64f130875600d90205adb7c23/src/Microsoft.Build.Sql/sdk/Sdk.props#L35
  -->
  <ItemGroup>
    <Build Include="**/*.sql" />
    <Build Remove="bin/**/*.sql" />
    <Build Remove="obj/**/*.sql" />
    <!-- Also Build Remove any .sql file patterns you want to exclude   e.g. -->
    <Build Remove="StaticDataScriptsReferencedInPostDeploy/**/*.sql" />

    <!-- Explicitly include your folders so that VisualStudio SSDT will display your files -->
    <Folder Include="OtherFolder" />
    <Folder Include="StaticDataScriptsReferencedInPostDeploy" />
    <Folder Include="Tables" />

    <None Include="README.md" />
    <None Include="StaticDataScriptsReferencedInPostDeploy/**/*.sql" />
  </ItemGroup>

  <ItemGroup>
    <PostDeploy Include="Script.PostDeployment.sql" />
  </ItemGroup>

  <!-- 
    Building through visual studio (targeting net48) will fail if a previous build through the dotnet core cli
    has run and created the obj/project.assets.json file. This custom target should delete
    the file before the visual studio build starts.
  -->
  <Target Name="PreBuild" BeforeTargets="PreBuildEvent" Condition="'$(MSBuildRuntimeType)' != 'Core'">
    <Message Importance="high" Text="Ensuring the $(MSBuildThisFileDirectory)\obj\project.assets.json file is removed, if necessary, so that the database project can be built through VisualStudio SSDT without errors" />
    <Delete Files="$(MSBuildThisFileDirectory)\obj\project.assets.json" />
  </Target>

</Project>
```

**Comment by ErikEJ** [comment]
@RyanThomas73 Thanks for sharing!

**Comment by RyanThomas73** [comment]
@EklipZgit 
The bottom of the convert existing doc you linked does already state part of the steps needed here `Even though build will honor the default globbing pattern, .sql files that are not included explicitly will not be displayed inside Solution Explorer in SSDT. Support for this will be added in a future release of SSDT`

That being said, the .md doc could benefit from that callout about using it in conjunction with SSDT 
1. Being moved to the top of the doc 
2. And being made more visually prominent
3. And including a link to this thread so readers can find the latest and greatest comments on workarounds consumers have found

**Comment by czb182** [comment]
Tried 1.19-preview with vs2022 17.10.1

get  (d
efault target) (14) ->
(ResolveNuGetPackageAssets target) ->
  C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Microsoft\NuGet\17.0\Microsoft.NuGet.targets(198,5):
 error : Your project does not reference ".NETFramework,Version=v4.7.2" framework. Add a reference to ".NETFramework,Ve
rsion=v4.7.2" in the "TargetFrameworks" property of your project file and then re-run NuGet restore.

If I try passing "/p:NetCoreBuild=true" to get around, get this isntead

  C:\Users\cmire\.nuget\packages\microsoft.build.sql\0.1.19-preview\Sdk\Sdk.targets(52,3): error MSB4019: The imported project "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.DefaultAssemblyInfo.targets" was not found. Confirm that the expression in the Import declaration "C:\Program Files\Microsoft Visual Studio\20
22\Enterprise\MSBuild\Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.DefaultAssemblyInfo.targets" is correct, and that the file exists on disk.

**Comment by andrew-sumner** [comment]
Tried 1.19-preview with vs2022 17.10.2 (Community Edition)

Failed with `MSB3030: Could not copy the file "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.8\normnfd.nlp" because it was not found.`

Logs:
```text
Rebuild started at 11:05 pm...
------ Rebuild All started: Project: ProductDatabase, Configuration: Debug Any CPU ------
		Ensuring the C:\Work\SQLExample\ProductDatabase\\obj\project.assets.json file is removed, if necessary, so that the database project can be built through VisualStudio SSDT without errors
		C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\Roslyn\csc.exe /noconfig /nowarn:NU5128,1701,1702,2008 /fullpaths /nostdlib+ /errorreport:prompt /warn:4 /define:DEBUG;TRACE /errorendlocation /preferreduilang:en-US /highentropyva+ /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.8\mscorlib.dll" /debug+ /debug:full /optimize- /out:obj\Debug\ProductDatabase.dll /subsystemversion:6.00 /target:library /warnaserror- /utf8output /langversion:7.3 "C:\Users\andre\AppData\Local\Temp\.NETFramework,Version=v4.7.2.SqlClrAttributes.cs"
		Loading project references...
		Loading project files...
		Building the project model and resolving object interdependencies...
		Validating the project model...
		Writing model to C:\Work\SQLExample\ProductDatabase\obj\Debug\Model.xml...
C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(4983,5): Error:  MSB3030: Could not copy the file "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.8\normnfd.nlp" because it was not found.
C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(4983,5): Error:  MSB3030: Could not copy the file "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.8\normnfc.nlp" because it was not found.
C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(4983,5): Error:  MSB3030: Could not copy the file "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.8\normnfkc.nlp" because it was not found.
C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(4983,5): Error:  MSB3030: Could not copy the file "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.8\normidna.nlp" because it was not found.
C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(4983,5): Error:  MSB3030: Could not copy the file "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.8\normnfkd.nlp" because it was not found.
Done building project "ProductDatabase.sqlproj" -- FAILED.
```

Using project file based on what @RyanThomas73 provided.

```xml
<?xml version="1.0" encoding="utf-8"?>
<Project DefaultTargets="Build">
  <Sdk Name="Microsoft.Build.Sql" Version="0.1.19-preview" />
  <PropertyGroup>
    <Name>Product Database</Name>
    <ProjectGuid>{3ed9c874-1009-4efe-8eb5-00fea496dfd8}</ProjectGuid>
    <DSP>Microsoft.Data.Tools.Schema.Sql.Sql160DatabaseSchemaProvider</DSP>
    <ModelCollation>1033, CI</ModelCollation>
    <TargetDatabaseSet>True</TargetDatabaseSet>

    <!-- Nuget specific tags -->
    <PackageId>My.Databases.Product</PackageId>
    <Version>$(Version)</Version>
    <Authors>Andrew Sumner</Authors>
    <Owners>Andrew Sumner</Owners>
    <Company>Company Name</Company>
    <Product>Product Name</Product>
    <Description>Package for Product dacpac</Description>
    <Copyright>Copyright 2024</Copyright>
    
    <!-- Support Visual Studio: https://github.com/microsoft/DacFx/issues/180#issuecomment-2010033767 -->
    <TargetFrameworkVersion Condition="'$(MSBuildRuntimeType)' != 'Core'">v4.8</TargetFrameworkVersion>
    <TargetFrameworkProfile Condition="'$(MSBuildRuntimeType)' != 'Core'" />
  </PropertyGroup>
  <ItemGroup>
    <Folder Include="build\" />
    <Folder Include="Tables" />
    <Folder Include="Stored Procedures\" />
  </ItemGroup>
  <ItemGroup>
    <None Include="build\My.Databases.Product.targets" />
    <None Include="Product.publish.xml" />
    <Content Include="build/My.Databases.Product.targets" PackagePath="build/My.Databases.Product.targets" />
  </ItemGroup>
  <Target Name="BeforeBuild">
    <Delete Files="$(BaseIntermediateOutputPath)\project.assets.json" />
  </Target>
  
  <!-- Support Visual Studio: https://github.com/microsoft/DacFx/issues/180#issuecomment-2010033767 -->
  <ItemGroup>
    <Build Include="Stored Procedures/**/*.sql" />
    <Build Include="Tables/**/*.sql" />
  </ItemGroup>
  <Target Name="PreBuild" BeforeTargets="PreBuildEvent" Condition="'$(MSBuildRuntimeType)' != 'Core'">
    <Message Importance="high" Text="Ensuring the $(MSBuildThisFileDirectory)\obj\project.assets.json file is removed, if necessary, so that the database project can be built through VisualStudio SSDT without errors" />
    <Delete Files="$(MSBuildThisFileDirectory)\obj\project.assets.json" />
  </Target>
</Project>
```

**Comment by andrew-sumner** [comment]
While this has been an interesting exercise, Visual Studio still lacks nuget package support so guess I'm stuck waiting for an official release :-(

**Comment by dzsquared** [comment]
Preview support for the Microsoft.Build.Sql SDK is landing in Visual Studio *soon* - will update ya'll as soon as the first release goes out the door!

**Comment by dzsquared** [comment]
With Visual Studio 17.12 preview 2 - support for Microsoft.Build.Sql SDK-style projects is now available in preview for Visual Studio.

2 key limitations to note:
- in preview 2 the file extension for the project is `.sqlprojx` instead of `.sqlproj`
- to use side-by-side with the original SQL projects in Visual Studio, install separate instances of VS on your machine

blog: https://techcommunity.microsoft.com/t5/azure-sql-blog/preview-release-of-sdk-style-sql-projects-in-visual-studio-2022/ba-p/4240616

docs: https://aka.ms/ssdt-sdk-preview

**Comment by ErikEJ** [comment]
@dzsquared already?? 😉 - this is amazing!

**Comment by dzsquared** [comment]
> @dzsquared already?? 😉 - this is amazing!

it seems like just yesterday 0.1.1-alpha was released..... but according to my notes - https://www.nuget.org/packages/Microsoft.Build.Sql/0.1.1-alpha - it was almost 3 years ago 😄
