### ISSUE TITLE
NetStandard2.1 - Get compiler error: Reference to type 'ExportAttribute' claims it is defined in 'System.ComponentModel.Composition', but it could not be found

### ISSUE THREAD

**Issue by t-johnson** [microsoft/DacFx#194]
- SqlPackage or DacFx Version: 161.6374.0
- .NET Framework (Windows-only) or .NET Core: .NET Standard 2.1
- Environment (local platform and source/target platforms):

**Steps to Reproduce:**

1. Using Visual Studio 2022, create a new Class Library, targeting .NET Standard 2.1
2. Add nuget package reference for Microsoft.SqlServer.DacFx, v 161.6374.0 (this is currently the latest version)
3. Add a dummy class that has a single ExportDeploymentPlanModifierAttribute.  the following one-liner is enough: 
 `[Microsoft.SqlServer.Dac.Deployment.ExportDeploymentPlanModifier("Dummy", "1.0.0.0")] public class Dummy { }`
4. Attempt to build - get a compiler error:
`error CS7069: Reference to type 'ExportAttribute' claims it is defined in 'System.ComponentModel.Composition', but it could not be found`
However I expected no errors.

**Did this occur in prior versions?  If not - which version(s) did it work in?**
This did not happen with nuget package version 150.5282.3
This error is shown for all 161.* versions of the package.

**Comment by t-johnson** [comment]
Workaround here seems to be adding a reference to the System.ComponentModel.Composition package to my own project.  seems a little odd as this is already listed as a dependency of the DacFX nuget package??

**Comment by zijchen** [comment]
There was a mismatch in the nuspec and our actual dependency to System.ComponentModel.Composition, should be fixed now. Can you give our latest preview version a try? [162.1.39-preview](https://www.nuget.org/packages/Microsoft.SqlServer.DacFx/162.1.39-preview)

**Comment by t-johnson** [comment]
@zijchen 
Just tried it, looks like there is no longer a problem. Thanks!
