### ISSUE TITLE
SSDT Project with 4 part name variables is showing a difference even though same dacpac is used

### ISSUE THREAD

**Issue by SeenaAugusty** [microsoft/DacFx#195]
- SqlPackage or DacFx Version: 161
- .NET Framework (Windows-only) or .NET Core: Any
- Environment (local platform and source/target platforms):

**Steps to Reproduce:**

1. Create SSDT ProjectB, referencing ProjectA using 4 part name variables as shown below:
![image](https://user-images.githubusercontent.com/113181575/206424079-75bb8752-3534-4142-a26a-37e07224929e.png)

2. Run sqlpackage.exe /Action:Script /SourceFile:"ProjectB.dacpac" /TargetFile:"ProjectB.dacpac" /TargetDatabaseName:"ProjectB" /OutputPath:"OutDiff.sql". The OutDiff.sql will have an alter view statement added to it eventhough the dacpac is same as shown below:
![image](https://user-images.githubusercontent.com/113181575/206425421-273bc432-a380-4d2c-895c-f52d0cdf4402.png)

**Did this occur in prior versions?  If not - which version(s) did it work in?** 

(DacFx/SqlPackage/SSMS/Azure Data Studio)

**Comment by sqltoolbox** [comment]
Great! thanks for all the help. Which release will this be heading into? I cannot see it labelled.

**Comment by SeenaAugusty** [comment]
It is available in VS 17.5 GA as well as VS 17.6 Preview 1 version

**Comment by sqltoolbox** [comment]
Hi @SeenaAugusty @llali was this eventually released as intended? How can I check which version of Visual Studio/SSDT/sqlpackage this went into?

**Comment by sqltoolbox** [comment]
I forgot to use the new parameter p:DoNotEvaluateSqlCmdVariables=False when executing sqlpackage.



I can confirm that this now works as intended!

Thanks!
