### ISSUE TITLE
Getting build error after selecting "automatically deploy the database project before unit tests are run" checkbox in SSDT visual studio 2022

### ISSUE THREAD

**Issue by abhi421** [microsoft/DacFx#200]
In new visual studio update “Microsoft Visual Studio Community 2022 (64-bit) - Current Version 17.4.3”,
After selecting the “automatically deploy the database project before unit tests are run” checkbox in SQL Server Test Configuration, when I tried to run the SQL unit test case I got the build error

` C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VisualStudio\v17.0\SSDT\Microsoft.Data.Tools.Schema.SqlTasks.targets(425,5): error MSB4062: The "SqlModelResolutionTask" task could not be loaded from the assembly C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\Extensions\Microsoft\SQLDB\DAC\Microsoft.Data.Tools.Schema.Tasks.Sql.dll. Method 'get_BuildEngine' in type 'Microsoft.Data.Tools.Schema.Tasks.Sql.SqlBuildTask' from assembly 'Microsoft.Data.Tools.Schema.Tasks.Sql, Version=17.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' does not have an implementation. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.`

Visual studio SQL Server Test Configuration option Screenshot
![image](https://user-images.githubusercontent.com/30606440/207865179-3bc3a859-e6b6-4067-a754-43f4ffaf6453.png)

Visual studio error Screenshot
![image](https://user-images.githubusercontent.com/30606440/207865385-8b8a9ae6-ef71-4502-b71d-8eaa8d5cc4d9.png)

**Comment by abhi421** [comment]
Microsoft QnA link for the same issue :-[Getting build error after selecting automatically deploy the database project before unit tests are run](https://learn.microsoft.com/en-us/answers/questions/1130501/getting-build-error-after-selecting-34automaticall.html)
Visual Studio Ticket for the same issue :- [Getting build error after selecting automatically deploy the database project before unit tests are run option](https://developercommunity.visualstudio.com/t/Getting-build-error-after-selecting-auto/10231857?ref=native&refTime=1671106047428&refUserId=8bc5a4b5-163e-6ceb-9cbe-0acd8e5b6ed6)

**Comment by kushabhi4u** [comment]
Hi
We are aware of this and constantly working on it all the updates will be shared on the Feedback ticket https://developercommunity.visualstudio.com/t/Getting-build-error-after-selecting-auto/10231857?ref=native&refTime=1671106047428&refUserId=8bc5a4b5-163e-6ceb-9cbe-0acd8e5b6ed6
