### ISSUE TITLE
Unable to specify TempDirectoryForTableData for Import action

### ISSUE THREAD

**Issue by ataidecarlos** [microsoft/DacFx#21]
TempDirectoryForTableData is available for Export action, and makes it possible to have a dedicated Folder/Drive to hold all the data, and is especially useful for very large databases, and not run out of space on the OS drive.

The same option should be available for Importing databases, can you consider this as a candidate to add the option?

**Comment by dzsquared** [comment]
Being added to documentation with https://github.com/MicrosoftDocs/sql-docs-pr/pull/24109
