### ISSUE TITLE
Parser fails on correct sql

### ISSUE THREAD

**Issue by generateui** [microsoft/DacFx#211]
- SqlPackage or DacFx Version: `161.6374.0`
- .NET Framework (Windows-only) or .NET Core: `6.0`
- Environment (local platform and source/target platforms): MacOS

**Steps to Reproduce:**

1. have sql alike
```sql
SET QUOTED_IDENTIFIER ON;
CREATE TABLE mytable
(
	  "id"  BIGINT IDENTITY(1,1) PRIMARY KEY
	, "col1" NVARCHAR(256) NOT NULL INDEX ix__mytable__col1__col2 NONCLUSTERED (col1) INCLUDE (col2)
	, "col2" VARBINARY(64) NOT NULL
)
```
2. parse using
```csharp
			// read file contents
			using var reader = new StringReader(content);
			var parser = new TSql160Parser(true);
			_ = parser.Parse(reader, out IList<ParseError> errors);
			errors.Should().BeEmpty();
```

Expected result: a parse tree
Actual result:
> Incorrect syntax near INCLUDE

Error number = 46010
```json
{
      Message = "Incorrect syntax near INCLUDE."
      Number = 46010
}
```
(Removed Column, Line, Offset because of code changes)

**Did this occur in prior versions?  If not - which version(s) did it work in?**
looks like other version of TSqlParser (i.e. TSql150Praser) also struggle with given sql

(DacFx/SqlPackage/SSMS/Azure Data Studio)
`<PackageReference Include="Microsoft.SqlServer.DacFx" Version="161.6374.0" />`

Azure data studio, visual studio seem to execute given sql fine.

**Comment by namangupta211** [comment]
Hi @generateui, can you please share the exact error you're getting while parsing?

**Comment by generateui** [comment]
The exact error message is noted in the above ticket: `"Incorrect syntax near INCLUDE."`, `46010`.
