### ISSUE TITLE
ScriptDom parser for Sql Server 2022 fails to parse LAG/LEAD with IGNORE NULLS clause

### ISSUE THREAD

**Issue by clement911** [microsoft/DacFx#213]
- DacFx Version: 161.6374.0 (Nuget)
-  .NET 7
- Windows 11

**Steps to Reproduce:**

After https://github.com/microsoft/DacFx/issues/133, the parser can parse IGNORE|RESPECT NULLS for FIRST_VALUE/LAST_VALUE but it still doesn't parse for LAG/LEAD

```csharp
using Microsoft.SqlServer.TransactSql.ScriptDom;

var parser = new TSql160Parser(true); //sql server 2022 parser
IList<ParseError> errors;

parser.ParseExpression(new StringReader("FIRST_VALUE(col) IGNORE NULLS OVER()"), out errors);
parser.ParseExpression(new StringReader("LAST_VALUE(col) IGNORE NULLS OVER()"), out errors);
//no parsing errors

parser.ParseExpression(new StringReader("LAG(col) IGNORE NULLS OVER()"), out errors);
parser.ParseExpression(new StringReader("LEAD(col) IGNORE NULLS OVER()"), out errors);
//parsing error! "Incorrect syntax near IGNORE." This should parse succesfully

Console.ReadLine();
```

(p.s.: Please open source the ScriptDom lib. It is full of bugs).

**Comment by ssreerama** [comment]
Added support for the Lag/Lead functions. And will be available with the upcoming release.

**Comment by clement911** [comment]
@ssreerama that's awesome.
It would probably make sense to tackle https://github.com/microsoft/DacFx/issues/181 at the same time..

**Comment by clement911** [comment]
Hi @ssreerama any updates on this?

**Comment by dzsquared** [comment]
Completed back in https://www.nuget.org/packages/Microsoft.SqlServer.TransactSql.ScriptDom/161.8812.0

**Comment by clement911** [comment]
Thank you @dzsquared 😀
