### ISSUE TITLE
Make Microsoft.SqlServer.TransactSql.ScriptDom a separate nuget package

### ISSUE THREAD

**Issue by clement911** [microsoft/DacFx#216]
Currently we use the nuget package `Microsoft.SqlServer.DacFx` but we only need the `Microsoft.SqlServer.TransactSql.ScriptDom` dll.

The `Microsoft.SqlServer.DacFx` package pulls a ton of DLLs that we don't need.
Would it be possible to release ScriptDom as a separate nuget package? (which DacFx could also depend on).

It would make our project much lighter/cleaner.

**Comment by llali** [comment]
ScriptDom now has it's own package https://www.nuget.org/packages/Microsoft.SqlServer.TransactSql.ScriptDom/161.8812.0
