### ISSUE TITLE
SqlServerCodeAnalysis rule custom project unable to be added to .sqlproj after converting to sdk style

### ISSUE THREAD

**Issue by rohkhann** [microsoft/DacFx#218]
I was trying to make my .sqlproj project use the sdk style preview following this doc: [Build a Project from the Command Line - Azure Data Studio | Microsoft Learn](https://learn.microsoft.com/en-us/sql/azure-data-studio/extensions/sql-database-project-extension-build-from-command-line?view=sql-server-ver15). I have some custom sqlserver rules run against my .sqlproj projects. the customsqlserverrules are in a class library following .net6.0
. When i move over to the below using the documentation i am continously stuck with the following build error: D:\..project.sqlproj : error NU1201: Project CustomSQLServerCodeAnaylsisRules is not comp
atible with net46 (.NETFramework,Version=v4.6)

I tried explicitly specifying the target version but it seems like it gets overridden by the version in the targets file of the sdk. 

Any help here would be appreciated.

**Comment by dzsquared** [comment]
pending new release of M.B.S with updated DacFx

**Comment by ErikEJ** [comment]
What is MBS?

**Comment by dzsquared** [comment]
@ErikEJ - sorry, was typing quickly and abbreviated Microsoft.Build.Sql as MBS
