### ISSUE TITLE
DacFX support for Certificate authentication.

### ISSUE THREAD

**Issue by chajonm** [microsoft/DacFx#222]
- SqlPackage or DacFx Version:160.6384.0.
- .NET Framework (Windows-only) or .NET Core: 4.6.2
- Environment (local platform and source/target platforms): Windows

I am trying to upgrade our app from version 150 to 160.6384.0.  

We use certificate authentication, so our connection string looks like this:

Data Source=tcp:chajononebox.redmond.corp.microsoft.com,1437;Initial Catalog=ClusterMetadataStore;Integrated Security=False;Pooling=False;Min Pool Size=1;Max Pool Size=330;Connect Timeout=30;Encrypt=True;TrustServerCertificate=False;Application Name="MS-CMS probe";Certificate=sha1:29EC2F3XYZ....

It looks like it DacFX is failing when parsing the connection string.   Is there something I can do or is this a bug?  
  
  <Message>Keyword not supported: 'certificate'.</Message>
  <Type>System.ArgumentException</Type>
  <StackTrace>   at Microsoft.Data.SqlClient.SqlConnectionStringBuilder.GetIndex(String keyword)
   at Microsoft.Data.SqlClient.SqlConnectionStringBuilder.set_Item(String keyword, Object value)
   at System.Data.Common.DbConnectionStringBuilder.set_ConnectionString(String value)
   at Microsoft.Data.SqlClient.SqlConnectionStringBuilder..ctor(String connectionString)
   at Microsoft.SqlServer.Dac.DacServices..ctor(String connectionString)

**Steps to Reproduce:**

1.  Have a SQL environment that requires certficiate authentication.
2.   DacServices dacServiceInstance = new DacServices(*a connection string specifying a certificate*);

**Did this occur in prior versions?  If not - which version(s) did it work in?** It works for 150.5282.3

(DacFx/SqlPackage/SSMS/Azure Data Studio)

**Comment by dzsquared** [comment]
Closing this issue as it is upstream from SqlClient (https://github.com/dotnet/SqlClient) and not likely to be fixed in future releases - I know @chajonm and others are in touch with that team.
