### ISSUE TITLE
Crash on build, but build maybe successful?

### ISSUE THREAD

**Issue by RobTF** [microsoft/DacFx#228]
- SqlPackage or DacFx Version: 0.1.9-preview
- .NET Framework (Windows-only) or .NET Core: 7.0.103 and 7.0.200-preview.22628.1
- Environment (local platform and source/target platforms): Windows 11

**Steps to Reproduce:**

1. Build my project
2. Observe failure message.

**Did this occur in prior versions?  If not - which version(s) did it work in?**
Unknown, only tried this version.

The output I get is;
```
                     Creating a model to represent the project... (TaskId:46)
                     Loading project references... (TaskId:46)
                     Loading project files... (TaskId:46)
                     Building the project model and resolving object interdependencies... (TaskId:46)
                     Validating the project model... (TaskId:46)
                     Writing model to C:\Repos\MyOrg\myorg-sqldb\MyOrg.Database\obj\Debug\Model.xml... (TaskId:46)
                     Writing create script to MyOrg.Database_Create.sql... (TaskId:46)
14:23:08.634   1:7>C:\Users\RobHarwood\.nuget\packages\microsoft.build.sql\0.1.9-preview\tools\netstandard2.1\Microsoft.Data.Tools.Schema.SqlTasks.targets(525,5): Build error : Object reference not set to an instance of an object. [C:\Repos\MyOrg\myorg-sqldb\MyOrg.Database\MyOrg.Database.sqlproj]
                     Output Item(s): 
                         FileWrites=
                             C:\Repos\MyOrg\myorg-sqldb\MyOrg.Database\obj\Debug\Model.xml
                             C:\Repos\MyOrg\myorg-sqldb\MyOrg.Database\obj\Debug\refactor.xml
                             C:\Repos\MyOrg\myorg-sqldb\MyOrg.Database\obj\Debug\postdeploy.sql
                             C:\Repos\MyOrg\myorg-sqldb\MyOrg.Database\obj\Debug\predeploy.sql
                             postdeploy.sql
                             refactor.xml (TaskId:46)
                   Done executing task "SqlBuildTask" -- FAILED. (TaskId:46)
```

A .dacpac does end up being generated as the failure seems to be very late in the build process. Is there any way to get a stack trace etc. out of this I can report? Thanks

**Comment by zijchen** [comment]
Hello, can you run `dotnet build` with parameters `-flp:diag -bl` and share the msbuild.log and msbuild.binlog files here?

**Comment by zijchen** [comment]
@RobTF I think I stumbled upon a repro for this issue. By any chance do you have a PackageReference to master.dacpac and `<GenerateCreateScript>True</GenerateCreateScript>` in your project?

**Comment by zijchen** [comment]
A workaround for this is to set `DatabaseVariableLiteralValue="master"` in the PackageReference
