### ISSUE TITLE
SSDT Code Analysis error SQL72039: The substring is out of the bounds for script MSSQL::xx occurs when SR0014 is enabled.

### ISSUE THREAD

**Issue by namangupta211** [microsoft/DacFx#235]
If we enable SR0014 in Code Analysis configuration in SSDT, then running Code Analysis fails.
The issue occurs when using temporal tables/history tables and based on the particular rule(SR0014) code Analysis is throwing the hard errors.

Steps to reproduce the problem or scenario:

1. Open/Create a sql database project having temporal/history tables to the machine with Visual 2022 installed.

2. In Solution Explorer, right-click on project , and then "Properties", then "Code Analysis" in the Project Settings window, and confirm that SR0014 is checked under Microsoft.Rules.Data.Design

3.  In Solution Explorer, right click on the project, then Click on "Run Code Analysis".

**Comment by tony-donley** [comment]
Thank you for working on this bug!  SR0014 is a critical code analysis rule that has been broken for several years now when using temporal tables.  I will be very happy to be able to use it again.
