### ISSUE TITLE
SQL Code Analysis Rules Not Run in dotnet Build

### ISSUE THREAD

**Issue by dhiraj-paryani** [microsoft/DacFx#237]
Hello team,

I have sqlproj with sdk style project.
I want to run sql anaylsis rules as part of the build, and I am using following in the sqlproj
```
<RunSqlCodeAnalysis>True</RunSqlCodeAnalysis>
<SqlCodeAnalysisRules>+!Microsoft.Rules.Data.SR0001</SqlCodeAnalysisRules>
```

But dontnet build is not running the sql code anaylsis rules, where as visual studio which uses msbuild runs these analysis rules and give build errors when there are some voilations.

dotnet command used: dotnet build /p:NetCoreBuild=true

**Comment by dzsquared** [comment]
Hi @dhiraj-paryani  - code analysis rules are not yet available for .NET Core.  I will get this noted as a needed improvement for the future. thanks!

**Comment by dhiraj-paryani** [comment]
Hi @dzsquared, do we have any timeline for when it will be supported?

**Comment by zijchen** [comment]
Added in 0.1.14-preview

**Comment by ErikEJ** [comment]
@dzsquared Does this mean that it is possible to author and load .NET (Core) based analysis rules now?

**Comment by ErikEJ** [comment]
@dzsquared The answer to my question was yes!
