### ISSUE TITLE
Dropping external tables while there are no changes

### ISSUE THREAD

**Issue by rkoumans** [microsoft/DacFx#249]
- SqlPackage or DacFx Version: latest
- .NET Framework (Windows-only) or .NET Core:
- Environment (local platform and source/target platforms):

**Steps to Reproduce:**

1. We release our database projects to Azure synapse through Azure Devops. In Azure Devops we use the 'Azure SQL Database deployment' task to do this. Since several weeks we notice that the deployment took much longer than before due to dropping every external table and re-create them while the are no changes made to the artifacts. 
When we do a deployment with the same publish script via Visual Studio the external tables won't be deleted.
2. This is the  "C:\Program Files\Microsoft SQL Server\160\DAC\bin\SqlPackage.exe" /Action:Publish /SourceFile:"D:\a\r1\a\Build Database Project\drop\Vebego Azure DWH\Database\bin\Output\Database.dacpac" /TargetServerName:"***" /TargetDatabaseName:"***" /TargetUser:"***" /TargetPassword:"********" /Profile:"D:\a\r1\a\Build Database Project\drop\Vebego Azure DWH\Database\Database.publish.xml" /Variables:AzureDataLakeStore=*** /Variables:AzureDatalakeCredential=*** /Variables:Environment=***

Publishing to database '***' on server '***'.
2023-04-04T08:40:03.4840777Z Initializing deployment (Start)
2023-04-04T08:40:51.4451578Z Initializing deployment (Complete)
2023-04-04T08:40:51.4458409Z Analyzing deployment plan (Start)
2023-04-04T08:40:51.7479428Z Analyzing deployment plan (Complete)
2023-04-04T08:40:51.7487033Z Updating database (Start)
2023-04-04T08:40:53.0604585Z Dropping External Table [stg].[Capacityd_xxxxx]...
2023-04-04T08:40:53.2690632Z Dropping External Table [stg].[Capacityd_xxxxxx]...
2023-04-04T08:40:53.4003746Z Dropping External Table [stg].[Capacityd_xxxx]...
.....
2023-04-04T08:41:54.0152301Z Creating External Table [stg].[Capacityd_xxxxxx]...
2023-04-04T08:41:55.2132575Z Creating External Table [stg].[Capacityd_xxxxxx]...
2023-04-04T08:41:56.0955483Z Creating External Table [stg].[Capacityd_xxxxxx]...

3.

**Did this occur in prior versions?  If not - which version(s) did it work in?**
We noticed this since 23-02-2023
(DacFx/SqlPackage/SSMS/Azure Data Studio)

**Comment by rkoumans** [comment]
@llali When will the lastest release be available? We still have the same issues

**Comment by SeenaAugusty** [comment]
@rkoumans does it have any differences in external data source or external file format that is linked to the external table?

**Comment by rkoumans** [comment]
@SeenaAugusty there are no differences in the external data source or external file format.
See the underlying scipts. We noticed this since 23-02-2023. The location of the external data source is a SQLCDM variable but contains the same value every deployment.

CREATE EXTERNAL TABLE [stg].[Capacityd_AssetCleaningHistory] (
    [AssetID] NVARCHAR (255) NULL,
    [CleanedBy] NVARCHAR (255) NULL,
    [CleaningTime] NVARCHAR (255) NULL,
    [KarID] NVARCHAR (255) NULL,
    [CustomerID] NVARCHAR (255) NULL,
    [AanleverDatum] DATETIME2 (7) NULL
)
    WITH (
    DATA_SOURCE = [AzureDataLakeStore],
    LOCATION = N'/Capacityd/AssetCleaningHistory',
    FILE_FORMAT = [Parquet]
    );
    
CREATE EXTERNAL FILE FORMAT [Parquet]
    WITH (
    FORMAT_TYPE = PARQUET,
    DATA_COMPRESSION = N'org.apache.hadoop.io.compress.SnappyCodec'
    );

      --Create External Data Source
      CREATE EXTERNAL DATA SOURCE AzureDataLakeStore
      WITH (
      TYPE = HADOOP,
      LOCATION = '$(AzureDataLakeStore)', 
      CREDENTIAL = AzureDatalakeCredential
      );

**Comment by SeenaAugusty** [comment]
@rkoumans Is the version of sqlpackage you have used is the latest 162.0.52 ?

**Comment by rkoumans** [comment]
our pipeline says the sqlpackage is: 16.1.8089.0
It seems MS has to update it's sqlpackage version or we have to install the latest version

**Comment by rkoumans** [comment]
upgrading to the last version works. No more unnecessary dropping of external tables.
Running the dacpac has become very slow

**Comment by thomas-svrts** [comment]
>  Running the dacpac has become very slow

Where you already able to resolves the extreme slowness?
