### ISSUE TITLE
SqlBuildTask uses the wrong name for the RecoveryMode property

### ISSUE THREAD

**Issue by kkloss-od** [microsoft/DacFx#250]
- SqlPackage Version: 16.1.8089.0
- DacFx Version: 161.8430.0-preview
- .NET Framework (Windows-only) or .NET Core: .NET Core
- Environment (local platform and source/target platforms): .NET SDK 6.0.407, SQL Server 2022 Standard

Setting the `Recovery` property for a sqlproj has no effect on the generated DACPAC. [According to the documentation](https://learn.microsoft.com/en-us/dotnet/api/microsoft.sqlserver.dac.model.databaseoptions.recoverymode?view=sql-dacfx-150#microsoft-sqlserver-dac-model-databaseoptions-recoverymode), the `DatabaseOptions` model class uses the property name `RecoveryMode`, but `Microsoft.Data.Tools.Schema.SqlTasks.targets` uses `Recovery` instead. Building the project completely omits the `RecoveryMode` element from the dacpac model.

**Steps to Reproduce:**

1. Add an entry to a `PropertyGroup` in the project file with: `<Recovery>Full</Recovery>`
2. Build the project
3. Open `model.xml` from the output dacpac and examine the `SqlDatabaseOptions` element.

**Did this occur in prior versions?** Unsure

DacFx

**Comment by zijchen** [comment]
It appears only `<Recovery>Full</Recovery>` is broken. If I set Recovery to `SIMPLE` or `BULK_LOGGED` the correct values are added to the model.xml.

**Comment by zijchen** [comment]
This is actually by design since the default recovery mode is `Full`. You can verify by creating an empty TSqlModel:
```cs
TSqlModel model = new TSqlModel(SqlServerVersion.SqlAzure, new TSqlModelOptions());
TSqlModelOptions options = model.CopyModelOptions();
Console.WriteLine(options.RecoveryMode);    // Should print "Full"
```
I also verified publishing the dacpac and the database options has full recovery mode set.

**Comment by kkloss-od** [comment]
Interesting. Works for me.
