### ISSUE TITLE
Non-default values in "SqlUserDefinedTypeAttribute" on SQL CLR User Defined Type class are not handled correctly

### ISSUE THREAD

**Issue by johangpettersson** [microsoft/DacFx#256]
- SqlPackage or DacFx Version: 16.1.8089.0 (sqlpackage installed through "dotnet tool install -g microsoft.sqlpackage")
- .NET Framework (Windows-only) or .NET Core: 7.0.203
- Environment (local platform and source/target platforms):
  - OS Version: Windows 11 (10.0.22621.1555)
  - Visual Studio Version: Microsoft Visual Studio Enterprise 2022 version 17.5.3
  - SQL Server Version: Microsoft SQL Server Developer (64-bit) version 14.0.3451.2

Setting SqlUserDefinedTypeAttribute properties on a SQL CLR User Defined types to non-default values does not seem to be handled correctly. An example would be setting "IsByteOrdered = true" for the type. The same issue seems to affect several actions in different ways:

- **Publish/script:** When updating an existing database using the same dacpac that created it, the update process drops and recreates the UDT eventhough there is no change to it. Depending objects such as tables having columns of the UDT are rebuilt.
- **Extract:** When extracting a dacpac from a database with an UDT as above, the attribute properties, such as "IsByteOrdered" is not set on the type in model.xml file in the dacpac.

**The .NET Framework build of SqlPackage (installed with MSI) seems to work as expected while the "dotnet tool"-build exhibits the behavior above.**

Example code can be found [here](https://github.com/johangpettersson/SqlPackageClrTest).

**Steps to Reproduce:**

1. Create new Sql Server Database Project
2. Set "Target platform" to "SQL Server 2017" and "Target framework" to ".NET Framework 4.8" (is not necessarily required but these are changes I had to make to adjust to my environment)
3. Add "SQL CLR User Defined Type" using the "Add New Item" dialog (under SQL Server -> SQL CLR C#)
4. Change the type attribute to: [Microsoft.SqlServer.Server.SqlUserDefinedType(Format.Native, IsByteOrdered = true)]
5. Create a table in the project with a column of the created UDT.
6. Build the database project to produce a dacpac.
7. Deploy the dacpac with: `sqlpackage /action:publish /TargetServerName:<servername> /TargetDatabaseName:<databasename> /SourceFile:<dacpacpath> /TargetEncryptConnection:false`
8. Generate an update script with exactly the same dacpac that created it against the created database: `sqlpackage /action:script /TargetServerName:<servername> /TargetDatabaseName:<databasename> /SourceFile:<dacpacpath> /TargetEncryptConnection:false /OutputPath:<scriptfilepath> /DiagnosticsFile:<logfilepath>`
  **Expected result:** The script should not contain any actions since the dacpac and the existing databases are identical.
  **Actual result:** The script drops and recreates the UDT and rebuilds the referencing table
9. Extract the database with: `sqlpackage /action:extract /SourceServerName:<servername> /SourceDatabaseName:<databasename> /TargetFile:<pathtoextracteddacpac> /SourceEncryptConnection:false /DiagnosticsFile:<logfilepath>`
10. Compare the original dacpac and the extracted dacpac using the Tools -> SQL Server -> New Schema Comparision in Visual Studio.
  **Expected result:** No differences with regards to the UDT or the referencing table should be found. The representation of the type in the model.xml file in the extracted dacpac should include the property "IsByteOrdered" with the value "true".
  **Actual result:** The UDT differs on the property "IsByteOrdered". In the original dacpac it is "true" while it is missing, null, in the extracted dacpac. The representation of the UDT in model.xml does not have any properties except "ClassName".

My suspicion is that this is symptoms of the same problem extracting the properties, among them "IsByteOrdered", of the UDT from an existing database. Are CLR types not supported when running this version of SqlPackage/DacFx?

Running the above actions using the DacServices class in a test console program (included in example code) seems to give further clues when debugging and "Break when thrown" has "All Common Runtime Exceptions not in this list" set.

When running DacServices.Script:

> Microsoft.Data.Tools.Schema.Sql.SqlClr.SqlClrException
>   HResult=0x80131500
>   Message=An unexpected error occurred. Contact product support for assistance.
>   Source=Microsoft.Data.Tools.Schema.Sql
>   StackTrace:
>    at Microsoft.Data.Tools.Schema.Sql.SqlClr.AssemblyParser.Process(String filename, IDictionary`2 clrToSqlTypes)
> 
>   This exception was originally thrown at this call stack:
>     System.Reflection.Assembly.GetTypes() in Assembly.cs
>     Microsoft.Data.Tools.Schema.Sql.SqlClr.AssemblyParser.Process(string, System.Collections.Generic.IDictionary<string, Microsoft.Data.Tools.Schema.Sql.SqlClr.ClrTypeSpecifier>)
> 
> Inner Exception 1:
> ReflectionTypeLoadException: Unable to load one or more of the requested types.
> Could not load file or assembly 'System.Data.SqlClient, Version=0.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
> Could not load file or assembly 'System.Data.SqlClient, Version=0.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
> Could not load file or assembly 'System.Data.SqlClient, Version=0.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
> Could not load file or assembly 'System.Data.SqlClient, Version=0.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
> Could not load file or assembly 'System.Data.SqlClient, Version=0.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
> Could not load file or assembly 'System.Data.SqlClient, Version=0.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
> Could not load file or assembly 'System.Data.SqlClient, Version=0.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
> Could not load file or assembly 'System.Data.SqlClient, Version=0.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
> Could not load file or assembly 'System.Data.SqlClient, Version=0.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
> Could not load file or assembly 'System.Data.SqlClient, Version=0.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
> 
> 
> Microsoft.Data.Tools.Schema.Sql.SqlClr.SqlClrException
>   HResult=0x80131500
>   Message=An unexpected error occurred. Contact product support for assistance.
>   Source=Microsoft.Data.Tools.Schema.Sql
>   StackTrace:
>    at Microsoft.Data.Tools.Schema.Sql.SqlClr.AssemblyParser.Process(String filename, IDictionary`2 clrToSqlTypes)
> 
>   This exception was originally thrown at this call stack:
>     Microsoft.Data.Tools.Schema.Sql.SqlClr.AssemblyParser.ProcessClrType(System.Collections.Generic.List<System.Reflection.Assembly>, Microsoft.Data.Tools.Schema.Sql.SqlClr.ClrAssembly, System.Type, System.Collections.Generic.List<System.Tuple<Microsoft.Data.Tools.Schema.Sql.SqlClr.ClrUserDefinedType, System.Type>>)
>     Microsoft.Data.Tools.Schema.Sql.SqlClr.AssemblyParser.Process(string, System.Collections.Generic.IDictionary<string, Microsoft.Data.Tools.Schema.Sql.SqlClr.ClrTypeSpecifier>)
> 
> Inner Exception 1:
> PlatformNotSupportedException: CLR types are not supported on .NET Core.

When running DacServices.Extract:

> Microsoft.Data.Tools.Schema.Sql.SqlClr.SqlClrException
>   HResult=0x80131500
>   Message=An unexpected error occurred. Contact product support for assistance.
>   Source=Microsoft.Data.Tools.Schema.Sql
>   StackTrace:
>    at Microsoft.Data.Tools.Schema.Sql.SqlClr.AssemblyParser.Process(String filename, IDictionary`2 clrToSqlTypes)
> 
>   This exception was originally thrown at this call stack:
>     System.Reflection.Assembly.GetTypes() in Assembly.cs
>     Microsoft.Data.Tools.Schema.Sql.SqlClr.AssemblyParser.Process(string, System.Collections.Generic.IDictionary<string, Microsoft.Data.Tools.Schema.Sql.SqlClr.ClrTypeSpecifier>)
> 
> Inner Exception 1:
> ReflectionTypeLoadException: Unable to load one or more of the requested types.
> Could not load file or assembly 'System.Data.SqlClient, Version=0.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
> Could not load file or assembly 'System.Data.SqlClient, Version=0.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
> Could not load file or assembly 'System.Data.SqlClient, Version=0.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
> Could not load file or assembly 'System.Data.SqlClient, Version=0.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
> Could not load file or assembly 'System.Data.SqlClient, Version=0.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
> Could not load file or assembly 'System.Data.SqlClient, Version=0.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
> Could not load file or assembly 'System.Data.SqlClient, Version=0.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
> Could not load file or assembly 'System.Data.SqlClient, Version=0.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
> Could not load file or assembly 'System.Data.SqlClient, Version=0.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
> Could not load file or assembly 'System.Data.SqlClient, Version=0.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
> 
> Microsoft.Data.Tools.Schema.Sql.SqlClr.SqlClrException
>   HResult=0x80131500
>   Message=An unexpected error occurred. Contact product support for assistance.
>   Source=Microsoft.Data.Tools.Schema.Sql
>   StackTrace:
>    at Microsoft.Data.Tools.Schema.Sql.SqlClr.AssemblyParser.Process(String filename, IDictionary`2 clrToSqlTypes)
> 
>   This exception was originally thrown at this call stack:
>     Microsoft.Data.Tools.Schema.Sql.SqlClr.AssemblyParser.ProcessClrType(System.Collections.Generic.List<System.Reflection.Assembly>, Microsoft.Data.Tools.Schema.Sql.SqlClr.ClrAssembly, System.Type, System.Collections.Generic.List<System.Tuple<Microsoft.Data.Tools.Schema.Sql.SqlClr.ClrUserDefinedType, System.Type>>)
>     Microsoft.Data.Tools.Schema.Sql.SqlClr.AssemblyParser.Process(string, System.Collections.Generic.IDictionary<string, Microsoft.Data.Tools.Schema.Sql.SqlClr.ClrTypeSpecifier>)
> 
> Inner Exception 1:
> PlatformNotSupportedException: CLR types are not supported on .NET Core.

**Did this occur in prior versions?  If not - which version(s) did it work in?**
N/A

**Comment by llali** [comment]
this is a known issue. When using dotnet tools, it install sqlpackage built by Net 6. SQL CLR are not supported in NetCore. use the Windows installer https://go.microsoft.com/fwlink/?linkid=2236347 to install sqlpackage built by Net 4.6.2

**Comment by johangpettersson** [comment]
Thank you for the answer!

I have a couple of thoughts though:

The current behavior does not seem desirable since SQL CLR appears to mostly work but under certain circumstances (like those reported here) it does not and it is not obvious why and what happened. To me it would seem better to make DacFx/SqlPackage report an error if trying to operate on a database with SQL CLR in it. There is a risk that users spend a lot of time to try to understand the situation otherwise.

What is the future for SQL CLR and .NET (NetCore)? Will SQL Server get support for SQL CLR using NetCore or will it be limited to .NET Framework? I realize that this is a question to big to answer here but can you point me to information about this?

If the scenario is that SQL CLR will be limited to .NET Framework: Does this also mean that the plan forward is that one can only use .NET Framework versions of DacFx (and SqlPackage) to deploy dacpacs containing SQL CLR? This is not an obvious connection to me: The component **_deploying_** dacpacs with SQL CLR must itself **_target_** .NET Framework. What is the reason for that?

**Comment by asrichesson** [comment]
Also ran into this today. NetCore sqlpackage will always drop and recreate SQLCLR classes when I have a property set on the SQLCLR attribute. For example:
```csharp
 [Microsoft.SqlServer.Server.SqlFunction(IsDeterministic = true)] --IsDeterministic, and any other property will trigger an update each time. 
 public static SqlString SqlFunction1()
 {
     return new SqlString (string.Empty);
 }
 
[Serializable]
[Microsoft.SqlServer.Server.SqlUserDefinedType(Format.Native, IsByteOrdered = true)] --IsByteOrdered will trigger an update
public struct SqlUserDefinedType1: INullable
{
}
```
However, NetFramework SqlPackage does not re-update these statements. I understand that sqlclr will probably always need to be built using .net framework for compatability with sqlserver. However, I would not expect that I have deploy the dacpac on windows using the .net framework version of sqlpackage. Maybe this should be more visible somewhere in the documentation. 

I would like to know the future plans for SQLCLR and if it will be supported on .net core at some point.
