### ISSUE TITLE
Table rebuild is spiking the deployment duration when the system versioned tabled with retention period set

### ISSUE THREAD

**Issue by ssreerama** [microsoft/DacFx#258]
- SqlPackage or DacFx Version: Both
- .NET Framework (Windows-only) or .NET Core: Both
- Environment (local platform and source/target platforms): All

**Steps to Reproduce:**

1. Make sure table has retention period set (HISTORY_RETENTION_PERIOD=6 MONTH) and is previously deployed like that.
2. Do any kind of change in the "Area" table, so publish script captures table changes (They did column reordering).
3. Generate publish script and observe part of script where Area table is recreated. The retention period is missing in ALTER statement. Due to that, after script publish, Area table will no longer have retention period set.
4. Same behavior when publishing from Visual Studio and Azure DevOps release pipeline (task “Azure SQL Database deployment”).
5. Above described issue is causing table rebuilding for system versioned tables, because DB project table schema still have retention period set in the code.

**Did this occur in prior versions?  If not - which version(s) did it work in?**

(DacFx/SqlPackage/SSMS/Azure Data Studio)

**Comment by StefanOverHaevgRZ** [comment]
@ssreerama @llali Is this fix released in https://www.nuget.org/packages/Microsoft.SqlServer.DacFx/162.0.52, or do we have to wait for the next version?

**Comment by llali** [comment]
@StefanOverHaevgRZ yes this is fixed in 162.0. If you still see the issue please let us know. Thanks
