### ISSUE TITLE
SqlPackage throws an exception when run through Process() and both error and output are redirected

### ISSUE THREAD

**Issue by argentini** [microsoft/DacFx#261]
- SqlPackage or DacFx Version: Latest version of SqlPackage available as a dotnet tools installation
- .NET Framework (Windows-only) or .NET Core: .NET 7.0.5
- Environment (local platform and source/target platforms): Windows 11

**Steps to Reproduce:**

1. The problem is outlined in this issue with CliWrap: [https://github.com/Tyrrrz/CliWrap/issues/205](https://github.com/Tyrrrz/CliWrap/issues/205)
2. Please look at the example code in this comment to reproduce the issue: [https://github.com/Tyrrrz/CliWrap/issues/205#issuecomment-1529037808](https://github.com/Tyrrrz/CliWrap/issues/205#issuecomment-1529037808)

**Did this occur in prior versions?  If not - which version(s) did it work in?**
I am not aware of this being an issue in previous SqlPackage versions.

**Comment by zijchen** [comment]
@argentini This is fixed and will be in the August release. Let me know if you want to try it out earlier and we can release a preview version of Microsoft.SqlPackage.
