### ISSUE TITLE
SQL71502 Error when using master SP

### ISSUE THREAD

**Issue by gsimantiras** [microsoft/DacFx#267]
Trying to migrate a database project to use dotnet build instead of MSBuild.

Using a master SP  like `sp_executesql` on a `sql1.sql` file
while using `<SuppressTSqlWarnings>71502</SuppressTSqlWarnings>` on specific file
with dotnet build still causes it to throw error (or warning depending on project properties)
while MSBuild did not throw.

**Comment by gsimantiras** [comment]
adding a clean repro case
https://github.com/gsimantiras/dbWithDacFxIssue/tree/main

**Comment by zijchen** [comment]
@gsimantiras You should be able to resolve this by adding a reference to the master.dacpac Nuget package:

```xml
<ItemGroup>
  <PackageReference Include="Microsoft.SqlServer.Dacpacs.Master" Version="160.0.0" DatabaseVariableLiteralValue="master" />
</ItemGroup>
```

**Comment by gsimantiras** [comment]
@zijchen thanks for the reply, but my project does not support Nuget Packages

**Comment by zijchen** [comment]
Package references should be supported in SDK version 0.1.7-preview and above, or can you not add package references as part of your larger build system?

**Comment by gsimantiras** [comment]
In my code example above, I am using that SDK
`<Sdk Name="Microsoft.Build.Sql" Version="0.1.9-preview" />`
but still Manage Nuget Packages firstly says "No projects supported by NuGet in the solution" and then it is disabled . 
I can add with `dotnet add package` command, but it's not working.

**Comment by dzsquared** [comment]
Hi @gsimantiras  - I'm going to close this out for now, but if you have output to share with @zijchen we'd be happy to look into it further
