### ISSUE TITLE
CREATE EXTERNAL FILE FORMAT not working with Synapse Serverless

### ISSUE THREAD

**Issue by jds3d** [microsoft/DacFx#269]
- SqlPackage or DacFx Version: 162.0.52
- .NET Framework (Windows-only) or .NET Core: 7.0.203
- Environment (local platform and source/target platforms): Powershell version 7.3.4 on Windows 11.

**Steps to Reproduce:**

1.  Open powershell
2. Execute 'dotnet new install Microsoft.Build.Sql.Templates'
3. Execute 'dotnet new sqlproj -n "Test" -tp SqlServerless'
4. Add a file called external_file format.sql to the directory with the Test.sqlproj file.
external_file_format.sql contains this:
CREATE EXTERNAL FILE FORMAT DeltaFormat
WITH
(
FORMAT_TYPE = DELTA
);
GO

5. Execute 'dotnet build' in that same directory from Powershell.
You should get this error:
C:\Users\[user]\source\repos\Test\External Resources\Environments\development\external_file_format.sql(1,1,1,1): Build error SQL70015: Statement 'CREATE EXTERNAL FILE FORMAT' is not supported for the targeted platform. [C:\Users\[user]\source\repos\Test\Test.sqlproj]

**Did this occur in prior versions?  If not - which version(s) did it work in?**
It has never worked.

(DacFx/SqlPackage/SSMS/Azure Data Studio)

**Comment by zijchen** [comment]
The fix for this is already checked in, but it missed the release by just a few days. It will be in the next release.

**Comment by jds3d** [comment]
Great!  Do you know when the next release will be?

**Comment by zijchen** [comment]
Next DacFx GA release isn't for another 2-3 months, but we can release another Microsoft.Build.Sql version sooner if enough updates go in.

**Comment by jds3d** [comment]
@zijchen How do you install Microsoft.Build.Sql?  I tried:

`PS C:\Users\Josh\source\repos\OWA> dotnet tool install Microsoft.Build.Sql -g --version 0.1.10-preview 
C:\Users\Josh\AppData\Local\Temp\0c1b8213-dbd7-44e6-b09b-b8daf6045388\restore.csproj : error NU1212: Invalid project-package combination for Microsoft.Build.Sql 0.1.10-preview. Dotnet
ToolReference project style can only contain references of the DotnetTool type
The tool package could not be restored.
Tool 'microsoft.build.sql' failed to install. This failure may have been caused by:

* You are attempting to install a preview release and did not use the --version option to specify the version.
* A package by this name was found, but it was not a .NET tool.
* The required NuGet feed cannot be accessed, perhaps because of an Internet connection problem.
* You mistyped the name of the tool.
`

**Comment by jds3d** [comment]
Ok great.  Sounds like I just need to sit back and wait for the next release then.  Presumably version 0.1.11-preview?

**Comment by zijchen** [comment]
Yes, we'll keep this issue open until a new version is released.
