### ISSUE TITLE
Add support for Enterprise SQL Server features (i.e. Indexes ONLINE=ON)

### ISSUE THREAD

**Issue by kramer1007** [microsoft/DacFx#27]
When building a SQL Server Database project, if SQL files include enterprise features such as Online Index building, these statements are ignored when outputting the SQL code or applying to target databases.

How to reproduce: add an index to a database project that would get deployed.  test it with "WITH (ONLINE = ON)" and without. You'll see that when looking at the output, you'll see that the "WITH (ONLINE = ON)" is ignored.

**Comment by kramer1007** [comment]
![image](https://user-images.githubusercontent.com/572879/226742145-a827c119-2937-40a3-8ca3-402fff0e8f7e.png)

**Comment by tony-donley** [comment]
Persisted options are honored or ignored according to publish profile flags, but non-persisted options are always ignored.  I would like to see **SOME** non-persisted options honored, such as ONLINE and  SORT_IN_TEMPDB.  DROP_EXISTING would need to be applied intelligently because it would fail if the index doesn't exist.

**Comment by kramer1007** [comment]
![image](https://github.com/microsoft/DacFx/assets/572879/22a2daf0-94bd-42cf-a305-8b4d7659e1f5)

**Comment by kramer1007** [comment]
![image](https://github.com/microsoft/DacFx/assets/572879/172ff496-957e-441b-8714-f5a7dc971d6f)

**Comment by kramer1007** [comment]
Great points Tony! I would have to agree with those options as well.

![image](https://github.com/microsoft/DacFx/assets/572879/c2f9fac3-25da-4670-9c07-b33f5d385cb1)

**Comment by asrichesson** [comment]
It would be nice to have an option in the publish profile to create all indexes with `ONLINE = ON` regardless if the option is not set in the Create Index DDL statement. Right now, I am using [this](https://github.com/DacFxDeploymentContributors/Contributors/tree/master/src/EditionAwareCreateIndex) contributor to set `ONLINE = ON` for all create index statements.

**Comment by llali** [comment]
this feature is implemented in dacFx and available in the preview version 162.2.91-preview

**Comment by dzsquared** [comment]
Support for applying the non-persistent ONLINE index option has been added in SqlPackage 162.2, releasing this morning.  

There will be a blog post shortly with more details, but there's 2 layers of control over the behavior:
1. A command line publish property (`/p:PerformIndexOperationsOnline`) can be set to true, which will apply to eligible index operations for that deployment.
2. `ONLINE = ON` or `ONLINE = OFF` statements on indexes in a SQL project will be incorporated in the compiled model (.dacpac) and when the dacpac is published those options override any command line options.  The SQL projects functionality is available in the next Microsoft.Build.Sql SDK version (very soon).  For use with the original SQL projects, it will roll to the different tools - Azure Data Studio will be the first (very soon) and SSDT will come with a future preview of Visual Studio 17.10.



I noticed that there was some discussion here about other non-persisted options - we would be happy to discuss any of those individually in new issues! (I ask for individually so we can be sure to determine and confirm the right behavior for each one)

**Comment by namangupta211** [comment]
[like]  Naman Gupta reacted to your message:
________________________________

**Comment by maciejw** [comment]
are you considering adding other options such as mentioned `DROP_EXISTING` in other comments? lack of this feature makes dacpacs kind of useless when you have SQL Enterprise... and you have to write custom contributors or change scripts by hand...

**Comment by dzsquared** [comment]
@maciejw - there are quite a few future improvements for DacFx under consideration, so I'd highly recommend that any specific options you're most interested in get filed as new issues

> I noticed that there was some discussion here about other non-persisted options - we would be happy to discuss any of those individually in new issues! (I ask for individually so we can be sure to determine and confirm the right behavior for each one)

for example, #483 was added

**Comment by maciejw** [comment]
> @maciejw - there are quite a few future improvements for DacFx under consideration, so I'd highly recommend that any specific options you're most interested in get filed as new issues

here you go https://github.com/microsoft/DacFx/issues/488

**Comment by jvdslikke** [comment]
Hi all, a bit late since this feature is already added, but this can also be accomplished with the ELEVATE_ONLINE database scoped configuration setting: https://learn.microsoft.com/en-us/sql/t-sql/statements/alter-database-scoped-configuration-transact-sql?view=sql-server-ver16#elevate_online---off--when_supported--fail_unsupported-

**Comment by asrichesson** [comment]
I wish `/p:PerformIndexOperationsOnline=True`  would override any indexes manually set to (ONLINE = OFF). A common problem is a dev exporting a table or an index exported through Azure Data Studio or SSMS, which defaults the indexes to ONLINE = OFF.
eg 
```sql
CREATE UNIQUE NONCLUSTERED INDEX [MyIndex] ON [dbo].[MyTable]
(
	[MyCol] ASC,
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
```
Unbeknownst to the dev, they have forced the deployment plan to deploy this index offline. So I'm still forced to either write a DacFx Contributor to either block indexes with (ONLINE = OFF) or automatically convert all Indexes to deploy (ONLINE = ON). Either way, I still can't use this feature out of the box.

**Comment by ErikEJ** [comment]
@asrichesson or create an analyzer rule? That will catch this very early in the process
