### ISSUE TITLE
Package reference interferes with artifact reference in Microsoft.Build.Sql 0.1.9-preview

### ISSUE THREAD

**Issue by lepagea01** [microsoft/DacFx#273]
- SqlPackage or DacFx Version: 161.8089.0
- .NET Framework (Windows-only) or .NET Core: dotnet 7.0.203 + Microsoft.Build.Sql 0.1.9-preview
- Environment (local platform and source/target platforms): MacOS Ventura 13.3 (development & build), Synapse Dedicated SQL Pool (deployment target)

**Steps to Reproduce:**

I don't know whether this new behaviour, introduced in version __0.1.9-preview__ of __Microsoft.Build.Sql__ is as expected, is a bug, or if the documentation about [package references](https://learn.microsoft.com/en-us/sql/azure-data-studio/extensions/sql-database-project-extension-sdk-style-projects?view=sql-server-ver16#package-references) is simply misleading.

I have a SDK-style database project that references the __master__ database (sys catalog views) in a Synapse Dedicated SQL Pool. Up until now, references were established in the `.sqlproj` file as follows:

```xml
<ItemGroup>
  <ArtifactReference Include="$(PkgMicrosoft_SqlServer_Dacpacs_Synapse)\tools\master.dacpac">
    <SuppressMissingDependenciesErrors>False</SuppressMissingDependenciesErrors>
    <DatabaseVariableLiteralValue>master</DatabaseVariableLiteralValue>
  </ArtifactReference>
</ItemGroup>
<ItemGroup>
  <PackageReference Include="Microsoft.SqlServer.Dacpacs.Synapse" Version="130.0.0" GeneratePathProperty="true" />
</ItemGroup>
```

The package reference enabled downloading the master.dacpac, as a NuGet package by running commands such as `dotnet restore` or `dotnet build`. The artifact/database reference enabled intellisense in, say, VS Code. Everything was working fine with version of __0.1.7-preview__ of __Microsoft.Build.Sql__ and likely previous versions. I can't recall.

My understanding is that version __0.1.9-preview__ of __Microsoft.Build.Sql__ enabled setting database reference attributes, `DatabaseVariableLiteralValue` for instance, as package references. However, keeping both artifact/database and package references as in the example above while upgrading __Microsoft.Build.Sql__ to __0.1.9-preview__ leads to deployment errors (not build errors). `sqlpackage /Action:Publish` then raises validation errors during the deployment analysis step, claiming for instance that required sys catalog views do not exist. Indeed, by analyzing the `model.xml` file in the __dacpac__ produced while building my project, one can see that the `<Metadata Name="ExternalParts" Value="[master]" />` element is missing.

There's an easy workaround. Simply add the `DatabaseVariableLiteralValue` to the package reference as well. Setting this attribute only in the artifact/database reference is no longer enough.

Again, I'm not sure if this situation requires a fix or more detailed documentation.

Thanks,

**Did this occur in prior versions?  If not - which version(s) did it work in?**
This behaviour was introduced in version __0.1.9-preview__ of __Microsoft.Build.Sql__.

(DacFx/SqlPackage/SSMS/Azure Data Studio)

**Comment by jthapa01** [comment]
@lepagea01  you said add the reference like below for workaround? can you add DatabaseVariableLiteralValue property in sdk base project?
<ItemGroup>
  <PackageReference Include="Microsoft.SqlServer.Dacpacs.Synapse" Version="130.0.0" GeneratePathProperty="true"  DatabaseVariableLiteralValue="master" />
</ItemGroup>

**Comment by zijchen** [comment]
@lepagea01 Sorry for the confusion on the docs--we'll update it as it's outdated already. You don't need the ArtifactReference any more if you have the PackageReference already. As @jthapa01 pointed out, this alone should be sufficient:
```xml
<ItemGroup>
  <PackageReference Include="Microsoft.SqlServer.Dacpacs.Synapse" Version="130.0.0" GeneratePathProperty="true"  DatabaseVariableLiteralValue="master" />
</ItemGroup>
```

**Comment by lepagea01** [comment]
Yes, that's what I eventually figured out. I guess I could have written a short post just by mentioning that the attributes now handled by package references, present or not, override the same attributes of the artifact/database reference. Thanks.

**Comment by IVNSTN** [comment]
> You don't need the ArtifactReference any more if you have the PackageReference already
@zijchen maybe I'm doing something wrong but I can't make it work without ArtifactReference blocks defined together with PackageReference blocks. If I comment `ArtifactReference` blocks and keep `PackageReference` with `DatabaseSqlCmdVariable` value then build succeeds but I get hundreds of warnings about unresolved references. None of references to dacpac-dependencies get resolved. If I keep both then warnings disappear. But I haven't tried to deploy build by SDK dacpacs yet.

SDK version: 0.1.23-preview
