### ISSUE TITLE
SDK based project does not cover the transitive dependencies on the project reference

### ISSUE THREAD

**Issue by jthapa01** [microsoft/DacFx#278]
- SqlPackage or DacFx Version:
- .NET Framework (Windows-only) or .NET Core:
- Environment (local platform and source/target platforms):

**Steps to Reproduce:**

1. Create the sql SDK based project (A). 
2. Create the .net project (B) that has reference to project A.
3. Create another .net project (C) that has reference to project B. After the build, project C's bin should have Project A's dll and dacpac

Any work around to define the above OutputPath property in directory.build.props?
Workaround is to add project reference at multiple places or manually copy the dacpac file.
(DacFx/SqlPackage/SSMS/Azure Data Studio)

**Comment by zijchen** [comment]
May be related to #117

**Comment by jthapa01** [comment]
> May be related to #117

So it's still not resolved?

**Comment by zijchen** [comment]
Not yet, I'll work on a fix for next release. It's interesting because passing it in from command line works, so it might be an ordering issue where a property is being overridden by its default.

**Comment by zijchen** [comment]
@jthapa01 I'm having trouble reproducing the issue, can you check if I'm missing something? I set up this repo with OutputPath set in Directory.Build.props, which is honored when I call `dontet build` on Database1

https://github.com/zijchen/DacFxIssue278

Can you also share which .NET SDK version and OS you're using? I tested with .NET 6 and 7 on Windows, both were working.

**Comment by jthapa01** [comment]
> @jthapa01 I'm having trouble reproducing the issue, can you check if I'm missing something? I set up this repo with OutputPath set in Directory.Build.props, which is honored when I call `dontet build` on Database1
> 
> https://github.com/zijchen/DacFxIssue278
> 
> Can you also share which .NET SDK version and OS you're using? I tested with .NET 6 and 7 on Windows, both were working.

We using msbuild to build the solution. Net6 on windows.

**Comment by zijchen** [comment]
I'm still not able to reproduce the issue with msbuild. What version of msbuild are you using? `msbuild /version`

Would you mind sharing a sample repro?

**Comment by jthapa01** [comment]
> I'm still not able to reproduce the issue with msbuild. What version of msbuild are you using? `msbuild /version`
> 
> Would you mind sharing a sample repro?

17.5.1.16304
