### ISSUE TITLE
Create a master key error in Azure devops

### ISSUE THREAD

**Issue by jthapa01** [microsoft/DacFx#279]
- SqlPackage or DacFx Version:
- .NET Framework (Windows-only) or .NET Core:
- Environment (local platform and source/target platforms):

**Steps to Reproduce:**

1. Upgrade old sql db proj to sdk based proj
2. Create or open a master key executing create certificate sql command in deployement.

```
<?xml version="1.0" encoding="utf-8"?>
<Project DefaultTargets="Build">
  <Sdk Name="Microsoft.Build.Sql" Version="0.1.9-preview" />
  <PropertyGroup>
    <Name>UADB</Name>
    <DSP>Microsoft.Data.Tools.Schema.Sql.SqlAzureV12DatabaseSchemaProvider</DSP>
    <ModelCollation>1033, CI</ModelCollation>
    <ProjectGuid>{d34-d3b-3bd0-89aa1-g87f7a}</ProjectGuid>
	<EnlistmentRoot>$(MSBuildThisFileDirectory)..\..</EnlistmentRoot>
    <Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
    <OutputPath>$(EnlistmentRoot)\bin\$(Name)\$(Configuration)</OutputPath>
    <TargetDatabaseSet>True</TargetDatabaseSet>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="AssemblyInfo.cs" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="System" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.SqlServer.Dacpacs.Azure">
      <GeneratePathProperty>true</GeneratePathProperty>
      <SuppressMissingDependenciesErrors>False</SuppressMissingDependenciesErrors>
      <DatabaseVariableLiteralValue>master</DatabaseVariableLiteralValue>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <PreDeploy Include="Scripts\PreDeployment.sql" />
    <PostDeploy Include="Scripts\PostDeployment.sql" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Scripts\" />
  </ItemGroup>
</Project>
```

```
CREATE CERTIFICATE [azdb]
    AUTHORIZATION [dbo]
    WITH SUBJECT = N'azdb', START_DATE = N'2021-01-01T01:00:00', EXPIRY_DATE = N'2022-01-01T01:00:00';
```

**Did this occur in prior versions?  If not - which version(s) did it work in?**
In old sql project it was building successfully. Updating the sql proj to SDK based fails on build executing the above sql command. 

Error SQL72014: Core Microsoft SqlClient Data Provider: Msg 15581, Level 16, State 1, Line 1 Please create a master key in the database or open the master key in the session before performing this operation. 

Error SQL72045: Script execution error. The executed script: refers to above script. Is this the ongoing bug?

(DacFx/SqlPackage/SSMS/Azure Data Studio)

**Comment by zijchen** [comment]
@jthapa01 Can you add more information about your build process? Is the `CREATE CERTIFICATE` script part of the sqlproj?

Build only generates .dacpac file and does not execute any SQL scripts, and the errors you posted are all SqlClient execution errors.

**Comment by jthapa01** [comment]
Found the bug on our end. Closing out this

**Comment by jthapa01** [comment]
Bug on our end.
