### ISSUE TITLE
DacPackage.UpdateModel() corrupts package, calling DacServices.GenerateDeployScript() fails afterwards.

### ISSUE THREAD

**Issue by smichtch** [microsoft/DacFx#281]
Creating a new issue from #242 per request from @zijchen

- SqlPackage or DacFx Version: `162.0.52`
- .NET Framework (Windows-only) or .NET Core: `net48` and `net6.0`
- Environment (local platform and source/target platforms): N/A

**Steps to Reproduce:**

The issue repros when targeting `net6.0` (likely netcoreapp3.1), it does not repro on `net4.8`:
```csharp
var dacpacFromSqlproj = "OutputOfSqlproj.dacpac";

using var buffer = new MemoryStream();
using (var temp = File.OpenRead(dacpacFromSqlproj))
{
    temp.CopyTo(buffer); // to avoid modifying the original .dacpac file
}

buffer.Position = 0;
using (var dacpac = DacPackage.Load(buffer, DacSchemaModelStorageType.Memory, FileAccess.ReadWrite))
{
    dacpac.UpdateModel(
        new TSqlModel(SqlServerVersion.SqlAzure, new TSqlModelOptions()),
        new PackageMetadata());
}

buffer.Position = 0;
using var dacpac2 = DacPackage.Load(buffer);

var dacServices = new DacServices(@"Data Source=(LocalDB)\MSSQLLocalDB;Integrated Security=true");

// Next line throws when on net6.0 but works on net4.8:
// Microsoft.SqlServer.Dac.DacServicesException: An error occurred during deployment plan generation.Deployment cannot continue.
// ---> Microsoft.Data.Tools.Schema.Sql.Deployment.DeploymentFailedException: The calculated checksum for model.xml in the package is different from the saved checksum.
// ---> Microsoft.Data.Tools.Schema.Sql.Build.SqlPackageException: The calculated checksum for model.xml in the package is different from the saved checksum.
dacServices.GenerateDeployScript(dacpac2, "TargetDatabaseName");
```

**Did this occur in prior versions?  If not - which version(s) did it work in?**
Prior versions of DacFx failed at the `DacPackage.Load(buffer)` step (after the `UpdateModel()` call) when on netcore 3.1 or net6.0, see #242 for details.
The issue repros on net6.0 runtime but not on net48.

(DacFx/SqlPackage/SSMS/Azure Data Studio)

**Comment by Ericvf** [comment]
If we are waiting until August for this release, then you might be interested to know that:

https://github.com/microsoft/DacFx/issues/242#issuecomment-1557104993

The workaround provided there also works for the checksum.

**Comment by zijchen** [comment]
We have fixed this issue and should be in the August release. Meanwhile you can give it a try with our preview release: [162.1.39-preview](https://www.nuget.org/packages/Microsoft.SqlServer.DacFx/162.1.39-preview)

**Comment by czb182** [comment]
I've been following dacfx development for a while, at least to me it seems to be moving faster.  Any chance of speeding up release cadence, maybe monthly or so? @zijchen

**Comment by dzsquared** [comment]
> I've been following dacfx development for a while, at least to me it seems to be moving faster. Any chance of speeding up release cadence, maybe monthly or so? @zijchen

I appreciate the sentiment that you're seeing faster development!  Our release cadence isn't set in stone, but I can't promise increasing the GA releases at the moment.
Are you looking for more frequent SqlPackage releases (as a preview), DacFx non-preview releases, or DacFx+SqlPackage non-preview releases?

**Comment by smichtch** [comment]
> We have fixed this issue and should be in the August release. Meanwhile you can give it a try with our preview release: [162.1.39-preview](https://www.nuget.org/packages/Microsoft.SqlServer.DacFx/162.1.39-preview)

@zijchen, I tried the new version and can confirm it works, thanks for getting this fixed!
