### ISSUE TITLE
XML_COMPRESSION = ON causes a table rebuild on every deploy

### ISSUE THREAD

**Issue by HamsterExAstris** [microsoft/DacFx#282]
- SqlPackage or DacFx Version: sqlpackage 19.2 and 162.0.52.1
- .NET Framework (Windows-only) or .NET Core: .NET Core
- Environment (local platform and source/target platforms): sqlpackage is run on Windows Server 2019 Datacenter with .NET Core 6.0.16 runtime. Target is Azure SQL Database.

When deploying a DACPAC file with a table with XML compression enabled (`CREATE TABLE ... WITH (XML_COMPRESSION = ON)`), sqlpackage is able to successfully rebuild the table to enable XML compression.

However, when *re*deploying that DACPAC to the same database, sqlpackage will do a table rebuild every single time, even if there's no schema changes.

Removing `WITH (XML_COMPRESSION = ON)` restores the expected behavior (i.e. it does not do a table rebuild on every deploy).

**Steps to Reproduce:**

1. Create a DACPAC with a table with XML compression enabled.
2. Deploy it to a database.
3. Redeploy it to the same database.

This only occurs when `WITH (XML_COMPRESSION = ON)` is set on the _table_ in the database project/DACPAC. When set on the _clustered index_, it does not exhibit this behavior.

Results in table rebuilds:
````
CREATE TABLE [dbo].[tablename] (
[Id]                              INT          IDENTITY (1, 1) NOT NULL,
[Inputs]                          XML          NULL,
CONSTRAINT [PK_tablename] PRIMARY KEY CLUSTERED ([Id] ASC)
) WITH (XML_COMPRESSION = ON);
````

Does not rebuild the table on every deploy:
````
CREATE TABLE [dbo].[tablename] (
[Id]                              INT          IDENTITY (1, 1) NOT NULL,
[Inputs]                          XML          NULL,
CONSTRAINT [PK_tablename] PRIMARY KEY CLUSTERED ([Id] ASC) WITH (XML_COMPRESSION = ON)
);
````

Both syntaxes are valid in SQL Server and appear to result in the same schema.

The one downside to the latter syntax is that it does not appear to apply XML compression if the table already exists, but only when creating the table. That's still better than *always* rebuilding the table, though.

**Did this occur in prior versions?  If not - which version(s) did it work in?** new functionality introduced in sqlpackage 19.2

**Comment by ssreerama** [comment]
Hey @HamsterExAstris,

I verified the issue with the previous and current versions of SqlPackage for both Full and Core versions and I don't see any rebuilding. Below is my steps and please let me know if I'm missing anything.

1. Created a DacPac with the XML_Compression (for this I used SqlProject to generate the dacpac).
2. `CREATE TABLE [dbo].[xml_compression_table] (
[Id] INT IDENTITY (1, 1) NOT NULL,
[Inputs] XML NULL,
CONSTRAINT [PK_tablename] PRIMARY KEY CLUSTERED ([Id] ASC) WITH (XML_COMPRESSION = ON)
);`
3. Deployed it to SQL Server 2022
4. Redeployed/ GeneratedScript with same dacpac without any updates on both dacpac/database, the resulted script is empty with no updates on the above table.

Can you please provide more details on how you generated the dacpac and how you are deploying it. Thanks

**Comment by dzsquared** [comment]
@HamsterExAstris - the team would love to dig deeper into this, but needs more info to understand why we cannot repro. thank you!

**Comment by ssreerama** [comment]
@HamsterExAstris, Since we do not hear back from you, closing this issue.

Please get back to us with the info we requested, and we can open this issue again to help you if the problem still exists. Thanks
