### ISSUE TITLE
Missing SQL Database options in dacpac for Microsoft Azure SQL Database target option in VS2022 17.5.5

### ISSUE THREAD

**Issue by namangupta211** [microsoft/DacFx#285]
We have a Visual Studio database project for which we also supply Query Store settings and MaxDop settings in the database settings Operational tab. The target platform we use in the project is “Microsoft Azure SQL Database”.

When we build the project with Visual Studio 17.4.4 the model.xml in the dacpac contains the supplied query store and max dop settings:
<Model>

<Element Type=“SqlDatabaseOptions”>

<Property Name=“Collation” Value=“Latin1_General_CI_AI” />

<Property Name=“IsAnsiNullDefaultOn” Value=“True” />

<Property Name=“IsAnsiNullsOn” Value=“True” />

<Property Name=“IsAnsiWarningsOn” Value=“True” />

<Property Name=“IsArithAbortOn” Value=“True” />

<Property Name=“IsConcatNullYieldsNullOn” Value=“True” />

<Property Name=“IsTornPageProtectionOn” Value=“False” />

<Property Name=“RecoveryMode” Value=“1” />

<Property Name=“IsFullTextEnabled” Value=“True” />

<Property Name=“IsTrustworthyOn” Value=“True” />

<Property Name=“IsAutoUpdateStatisticsAsyncOn” Value=“True” />

<Property Name=“PageVerifyMode” Value=“3” />

<Property Name=“DefaultLanguage” Value="" />

<Property Name=“DefaultFullTextLanguage” Value="" />

<Property Name=“QueryStoreDesiredState” Value=“2” />

<Property Name=“QueryStoreCaptureMode” Value=“2” />

<Property Name=“QueryStoreMaxStorageSize” Value=“512” />

<Property Name=“QueryStoreStaleQueryThreshold” Value=“90” />

<Property Name=“MaxDop” Value=“4” />

</Element>

However when we build the project with Visual Studio 17.5.5 those settings are missing from the model.xml:
<Model>

<Element Type=“SqlDatabaseOptions”>

<Property Name=“Collation” Value=“Latin1_General_CI_AI” />

<Property Name=“IsAnsiNullDefaultOn” Value=“True” />

<Property Name=“IsAnsiNullsOn” Value=“True” />

<Property Name=“IsAnsiWarningsOn” Value=“True” />

<Property Name=“IsArithAbortOn” Value=“True” />

<Property Name=“IsConcatNullYieldsNullOn” Value=“True” />

<Property Name=“IsTornPageProtectionOn” Value=“False” />

<Property Name=“RecoveryMode” Value=“1” />

<Property Name=“IsFullTextEnabled” Value=“True” />

<Property Name=“IsTrustworthyOn” Value=“True” />

<Property Name=“IsAutoUpdateStatisticsAsyncOn” Value=“True” />

<Property Name=“PageVerifyMode” Value=“3” />

<Property Name=“DefaultLanguage” Value="" />

<Property Name=“DefaultFullTextLanguage” Value="" />

</Element>

When we deploy the dacpac to our Azure Database it is reverting those settings to the default settings (MaxDop 8, QUeryStore Size 100 instead of the 512 we need).

As a temporary workaround we changed the targetplatform to “SQL Server 2022 or Azure SQL Database Managed Instance” since this does include those settings again.

**Comment by namangupta211** [comment]
Resolved.

**Comment by dzsquared** [comment]
This was shipped with DacFx 162.0.52 in May and is included in the Visual Studio 17.6 GA release.
