### ISSUE TITLE
SqlPackage does not deploy referenced DAC package

### ISSUE THREAD

**Issue by koryukov** [microsoft/DacFx#30]
### Summary

Although `IncludeCompositeObjects` is set to `true`, the  `SqlPackage` deploys only "main" DAC package.

### Environment

OS: Windows 10 Pro x64  
SQL Server version: 13.0.4001  
SqlPackage version: 15.0.5176.1

### Steps to reproduce

I have created a solution with two database projects: _Dependent.sqlproj_ and _Dependency.sqlproj_. The _Dependent.sqlproj_ references to _Dependency.sqlproj_:

```xml
<ItemGroup>
  <SqlCmdVariable Include="Dependency">
    <DefaultValue>Dependency</DefaultValue>
    <Value>$(SqlCmdVar__4)</Value>
  </SqlCmdVariable>
</ItemGroup>
<ItemGroup>
  <ProjectReference Include="..\Dependency\Dependency.sqlproj">
    <Name>Dependency</Name>
    <Project>{d635d16a-0d11-4c0a-b4c3-a646e442d8f4}</Project>
    <Private>True</Private>
    <SuppressMissingDependenciesErrors>False</SuppressMissingDependenciesErrors>
    <DatabaseSqlCmdVariable>Dependency</DatabaseSqlCmdVariable>
  </ProjectReference>
</ItemGroup>
```

After compitation of _Dependent.sqlproj_ the _bin_ folder looks fine, because it contains following files:

* Dependency.dacpac;
* Dependency.dll;
* Dependency.pdb;
* Dependent.dacpac;
* Dependent.dll;
* Dependent.pdb.

To deploy databases I use following PowerShell script:

```powershell
sqlpackage /a:Publish ^
  /sf:Dependent.dacpac ^
  /tsn:"(localdb)\MSSQLLocalDB" ^
  /tdn:Dependent ^
  /dsp:Deployment.sql ^
  /df:Deployment.log ^
  /p:IncludeCompositeObjects=true ^
  /v:Dependency=Dependency
```

### Expected behaviour

It should deploy _Dependent_ and _Dependency_ databases to the target server.

### Actual behaviour

It deploys only _Dependent_ database. _Deployment.sql_ also contains nothing about _Dependency_ database objects.

### Attachments

* [Deployment.log](https://github.com/microsoft/DACExtensions/files/7156004/Deployment.log);
* [Deployment.sql](https://github.com/microsoft/DACExtensions/files/7156016/Deployment.txt).

**Comment by kisantia** [comment]
This behavior is by design. If the referenced project is a "same project" reference, then it also gets published along with the main project getting published when IncludeCompositeObjects=true. The publish action only publishes to one database and external databases are effectively read-only.

In this case, the referenced project is to a different database, so the referenced project is expected to be published first before the project that references it.
