### ISSUE TITLE
Dacpac deployment of Synapse containing External tables runs very slow or does not complete

### ISSUE THREAD

**Issue by RichardBorges-AlintaEnergy** [microsoft/DacFx#300]
I had raised this issue with the runner-images team https://github.com/actions/runner-images/issues/7795

- SqlPackage or DacFx Version:  162.0.52.1
- .NET Framework (Windows-only) or .NET Core: .Net CORE
- Environment (local platform and source/target platforms): Azure hosted Synapse database

When deploying a Synapse database dacpac containing External Tables to an Azure hosted Synapse database, the Win 2019 image (which includes DacFx 162.0.52.1), simply takes a very long time ( 3 to 4 hours) when running the step for Schema compare:

`Microsoft.Data.Tools.Diagnostics.Tracer Verbose: 25 : 2023-06-27T16:59:01 : Perf: Operation started (name, details): CompareAllElementsForOneType,SqlSchema `

The previous version DacFx 161.8089.0 proceeds to successfully complete the SqlSchema check. The DacFx 162.0.52.1 version does not.

The successful command used is

```
"C:\Download\Microsoft\SQLPackage161.8089.0\SqlPackage.exe" /Action:Script /SourceFile:"C:\Temp\DacPacSynapseLocalBuild\synapse.dacpac" TargetServerName:"xxxxxadhaesqlsvr.database.windows.net" 
/TargetDatabaseName:"xxx-xxx-synapse" /TargetUser:"xxxxxxx" /TargetPassword:"*****" /Profile:"C:\Temp\DacPacSynapseLocalBuild\synapse_prod.publish.xml" /OutputPath:"C:\Temp\DacPacSynapseLocalBuild\Temp\adh-ae-synapse_Script.sql" /V:Environment=test /P:CommandTimeout=180 /TargetTimeout:120 /Diagnostics:True /DiagnosticsFile:"C:\Temp\DacPacSynapseLocalBuild\Temp\diag.log"  
```
Both Azure hosted runner 'Windows 2019' and 'Windows 2022' are failing the External Tables SqlSchema check.

**Platforms affected**
 Azure DevOps

**Runner images affected**
 Windows Server 2019
 Windows Server 2022

**Image version and build link**
Starting: Initialize job
Agent name: 'Hosted Agent'
Agent machine name: 'fv-az905-107'
Current agent version: '3.220.5'
Operating System
Runner Image
Runner Image Provisioner
Current image version: '20230620.1.0'
Agent running as: 'VssAdministrator'
Prepare build directory.
Set build variables.
Download all required tasks.
Downloading task: DownloadBuildArtifacts (1.220.0)
Downloading task: Bash (3.224.0)
Downloading task: AzureKeyVault (1.223.0)
Downloading task: SqlAzureDacpacDeployment (1.223.3)
Downloading task: SqlAzureDataWarehouseDacpacDeployment (1.0.2)
Downloading task: PublishPipelineMetadata (0.216.0)
Checking job knob settings.
Knob: DockerActionRetries = true Source: $(VSTSAGENT_DOCKER_ACTION_RETRIES)
Knob: AgentToolsDirectory = C:\hostedtoolcache\windows Source: ${AGENT_TOOLSDIRECTORY}
Knob: AgentPerflog = c:\vsts\perflog Source: ${VSTS_AGENT_PERFLOG}
Knob: ContinueAfterCancelProcessTreeKillAttempt = true Source: $(VSTSAGENT_CONTINUE_AFTER_CANCEL_PROCESSTREEKILL_ATTEMPT)
Finished checking job knob settings.
Start tracking orphan processes.
Finishing: Initialize job

**Is it regression?**
No

**Expected behavior**
The
task: SqlAzureDacpacDeployment@1
should create the database deployment script

**Actual behavior**
The
task: SqlAzureDacpacDeployment@1
hangs for hours at
Microsoft.Data.Tools.Diagnostics.Tracer Verbose: 25 : 2023-06-27T16:59:01 : Perf: Operation started (name, details): CompareAllElementsForOneType,SqlSchema

**Steps to Reproduce:**
1. Create a database project in VS2019
2. Containing External tables
3. Generate the dacpac file
4. Use SQLPackage.exe 162.0.52.1 to generate the database base script (comparing to a target Azure hosted Synapse database)

**Did this occur in prior versions?  If not - which version(s) did it work in?**
Dacpac deployment for Synapse with external tables works with version 161.8089.0 

(DacFx/SqlPackage/SSMS/Azure Data Studio)

**Comment by rkoumans** [comment]
I'm having the same problem. Please keep me posted

**Comment by rkoumans** [comment]
Is there any progress on this issue?

**Comment by SeenaAugusty** [comment]
@rkoumans Its fixed and its pending release

**Comment by dataniard** [comment]
Hi, @SeenaAugusty , when will this fix be released? We have the same issue in vscode, as it's using 16.0.9021. Are both projects aligned?

Regards
