### ISSUE TITLE
SDK-style sqlproj is not integrated well with VS 2019 Solution Explorer

### ISSUE THREAD

**Issue by IVNSTN** [microsoft/DacFx#307]
- SqlPackage /Version: 162.0.52.1
- .Net Framework Version: 4.8.03761
- dotnet --version: 6.0.400
- Environment:
  - Microsoft Visual Studio 2019 Community Edition 16.11.28
  - Microsoft.Build.Sql Version=0.1.10-preview (same on 0.1.9)
  - Windows7x64 in VirtualBox

**Steps to Reproduce:**

1. Get existing SSDT-style sqlproj, remove all the `<Build Include...`
2. Reload project in Visual Studio - Solution explorer shows only "References" and Folders without any file
3. Add `<Build Include="**\*.sql"/>` to sqlproj
4. Reload project in Visual Studio - Solution explorer now shows all files with respect to folder structure
5. Open several .sql files, switch between editor tabs
6. Solution explorer does not change focus position, file from currently active tab is not revealed in Solution Explorer

Thus there are several things:
- as said in the readme for this SDK _glob `**\*.sql`_ is respected but only during build, it has no effect in VS, you still need to include files manually into sqlproj at least with the same glob pattern
- activating tab does not lead to focus position change to the active file in Solution Explorer which is very uncomfortable

**Did this occur in prior versions?  If not - which version(s) did it work in?**

No working version found.

**Comment by ErikEJ** [comment]
@zijchen Are you palnning to support SDK style projects in VS 2019?

**Comment by CarlosOnline** [comment]
Please add support for Visual Studio.

**Comment by dzsquared** [comment]
Consolidating into #180
