### ISSUE TITLE
Microsoft.Build.Sql: does not work with NuGet centralized package management

### ISSUE THREAD

**Issue by Aaronontheweb** [microsoft/DacFx#316]
- SqlPackage or DacFx Version: 0.1.10-preview
- .NET Framework (Windows-only) or .NET Core: .NET 7.0
- Environment (local platform and source/target platforms): Windows, GitHub Actions on Ubuntu / Windows agents

**Steps to Reproduce:**

Using the following config in `Directory.Packages.props`:

```xml
<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <!-- SQL Build Tools -->
  <ItemGroup>
    <PackageVersion Include="Microsoft.Build.Sql" Version="0.1.10-preview" />
  </ItemGroup>
</Project>
```

And the following `.sqlproj` schema, created using the `dotnet new sqlproj` template:

```xml
<?xml version="1.0" encoding="utf-8"?>
<Project DefaultTargets="Build">
  <Sdk Name="Microsoft.Build.Sql"/>
  <PropertyGroup>
    <Name>Sdkbin.Database</Name>
    <DSP>Microsoft.Data.Tools.Schema.Sql.Sql160DatabaseSchemaProvider</DSP>
    <ModelCollation>1033, CI</ModelCollation>
  </PropertyGroup>
</Project>
```

And the following `global.json`:

```json
{
  "sdk": {
    "rollForward": "latestMinor",
    "version": "7.0.100"
  },
   "msbuild-sdks": {
        "Microsoft.Build.Sql": "0.1.10-preview"
    }
}
```

Running `dotnet build -c Release` produces the following error:

```
C:\Repositories\project\MyApp.Database.sqlproj : error NU1008: Projects tha t use central package version management should not define the version on the PackageReference items but on the Package Version items: Microsoft.NETFramework.ReferenceAssemblies.
    0 Warning(s)
    1 Error(s)
```

I tried working around this by updating `Directory.Packages.props` to:

```xml
<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <!-- SQL Build Tools -->
  <ItemGroup>
    <PackageVersion Include="Microsoft.Build.Sql" Version="0.1.10-preview" />
    <PackageVersion Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3" />
  </ItemGroup>
</Project>
```

But I still get the same build error.

**Did this occur in prior versions?  If not - which version(s) did it work in?**

Haven't used this tool before and this is a greenfield project, so I don't know.

**Comment by stroborobo** [comment]
As far as I understand NuGet expects PackageReferences and FrameworkReferences inside of Sdks to have IsImplicitlyDefined="true" set. A PackageVersion would not be needed then as well. 

Just thinking out loud: maybe this issue should not happen, because it's a side effect of importing Microsoft.Common.props, which is part of the .Net build. So not settings the target framework etc. makes it fall back to .Net Framework and complain.

**Comment by Aaronontheweb** [comment]
I was able to work around this by adding a new `Directory.Packages.props` file into the folder where just my DacFx project lives:

```xml
<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>false</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <!-- SQL Build Tools -->
  <ItemGroup>
    <PackageVersion Include="Microsoft.Build.Sql" Version="0.1.10-preview" />
    <PackageVersion Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3" />
  </ItemGroup>
</Project>
```

Disabling centralized NuGet package management there did the trick.

**Comment by znamenap** [comment]
I'm suggesting you to change it to this form:
` <ItemGroup>
    <PackageVersion Update="Microsoft.Build.Sql" Version="0.1.10-preview" />
    <PackageVersion Update="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3" />
  </ItemGroup>
`
Notice the change from Include to Update. You use Include form in the projects and Update+Version attributes at central place.
