### ISSUE TITLE
Schema Compare fails with "login failed for user <token-identified principal>"

### ISSUE THREAD

**Issue by srahlf** [microsoft/DacFx#328]
- Azure Data Studio Version: 1.45.1
- OS Version: Microsoft Windows 10 Enterprise
- Schema Compare extension: v1.20.0

Schema compare Azure SQL DB <> DB project cloned GIT fails with the login failure message. 
The connection can be used in Azure Data Studio without problems and SSMS works also fine on the same VDI/same credentials.
With previous version it worked fine. Colleagues still haven't upgraded can use it.
No clue why this is happening now.

The DB is a Azure SQL DB where the user is max db_owner as the AAD Admin is reserved for a service principal used in DevOps deploy. 

![Azure Data Studio Schema Compare Failure  2023-08-16](https://github.com/microsoft/azuredatastudio/assets/91253154/6327ddcf-47ab-401f-8451-9a1f9d5b7f17)

**Comment by kisantia** [comment]
Transferred this issue to the DacFx repo since this error only started being reported with the 1.45 ADS release, which updated the DacFx nuget version to 162.1.59-preview (previous ADS release used 162.0.34-preview). Let me know if there's anything I can help with for investigation on the ADS/STS side.

**Comment by Thamasky** [comment]
Experiencing the same issue

**Comment by Gorropla** [comment]
The solution was given with the update. Version: 1.46.0 (system setup)
Commit: 39449bbe88a0bc4092c9b205cad10d0a556beffd
Date: 2023-09-16T01:40:10.706Z
VS Code: 1.79.2
Electron: 22.3.14
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.22621

**Comment by kisantia** [comment]
Glad to hear this is fixed in the latest ADS release! We updated the DacFx version to 162.1.142-preview in the 1.46.0 ADS release, which must've brought in the fix.

Closing since this is reported as fixed in the latest ADS release.
