### ISSUE TITLE
Azure SQL Database deployment Task(Dacpac) issue

### ISSUE THREAD

**Issue by DhatyaSri** [microsoft/DacFx#331]
When we publish a Dacpac file through Azure SQL database deployment task(Dacpac) we are getting changes in syntax. 
And the same file we are unable to deploy in Azure DevOps .
Could not deploy package.
2023-07-04T11:11:14.6552264Z Error SQL72014: .Net SqlClient Data Provider: Msg 102, Level 15, State 1, Line 4 Incorrect syntax near ' '.
2023-07-04T11:11:14.6556024Z Error SQL72045: Script execution error. The executed script:

Getting above error while deploying the SQL DACPAC in azure devops

- SqlPackage or DacFx Version:
- .NET Framework (Windows-only) or .NET Core:
- Environment (local platform and source/target platforms):

**Steps to Reproduce:**

1.
2.

**Did this occur in prior versions?  If not - which version(s) did it work in?**

(DacFx/SqlPackage/SSMS/Azure Data Studio)

**Comment by ssreerama** [comment]
Hey @DhatyaSri , Can you provide us more details on the issue please, like dacfx version, repro steps, etc . Are you able to deploy the dacpac using SqlPackage.exe? If it still failing there too, can you provide us the errors generated in the diagnostic logs. Thanks.

**Comment by dzsquared** [comment]
hi @DhatyaSri  - would you be able to provide a few more details as @ssreerama mentioned?

**Comment by dzsquared** [comment]
hi @DhatyaSri - would you be able to provide a few more details?
