### ISSUE TITLE
Help needed: How to define multiple DacpacName from a single PackageReference?

### ISSUE THREAD

**Issue by IVNSTN** [microsoft/DacFx#342]
- SDK: 1.0.12-preview
- .NET Framework (Windows-only) or .NET Core:
- Environment (local platform and source/target platforms):
- windows

Docs say that I can do the following if I need one dacpac from a package with multiple dacpacs:
```
<PackageReference Include="Contoso.Applications" Version="160.0.0">
      <DacpacName>Outfitters</DacpacName>
</PackageReference>
```
But how should I refer two or three dacpacs from a package with let's say 5 dacpacs?
How to define `DatabaseSqlCmdVariable` for each dacpac from a single package?
How to define `DatabaseSqlCmdVariable`s if I need all 5 (or more) dacpacs from a package?

(DacFx/SqlPackage/SSMS/Azure Data Studio)

**Comment by zijchen** [comment]
@IVNSTN You would need to add the other dacpacs as ArtifactReferences, and you can define DatabaseSqlCmdVariable for each.

```xml
<PackageReference Include="Contoso.Applications" Version="160.0.0">
  <DacpacName>Outfitters</DacpacName>
  <GeneratePathProperty>true</GeneratePathProperty>
</PackageReference>
<ArtifactReference Include="$(PkgContoso_Applications)/tools/Dacpac2.dacpac">
  <DatabaseSqlCmdVariable>...</DatabaseSqlCmdVariable>
</ArtifactReference>
<ArtifactReference Include="$(PkgContoso_Applications)/tools/Dacpac3.dacpac">
   <DatabaseSqlCmdVariable>...</DatabaseSqlCmdVariable>
</ArtifactReference>
...
```

**Comment by IVNSTN** [comment]
@zijchen okay, but I don't quite understand this comment then - https://github.com/microsoft/DacFx/issues/273#issuecomment-1550405370
> You don't need the ArtifactReference any more if you have the PackageReference already

So are `ArtifactReference` and `PackageReference` supposed to be _mutually exclusive_ or SDK can successfully combine them as you mentioned in the comment above?

**Comment by IVNSTN** [comment]
_sorry for closing/reopening - just pressed wrong button._

**Comment by zijchen** [comment]
If your Nuget package only has 1 dacpac inside, the `PackageReference` can replace the `ArtifactReference` for that single dacpac. But if you have more than 1 dacpac, you'll still need to use `ArtifactReference` to add the rest. The 2 aren't mutually exclusive; `PackageReference` is just syntactic sugar for the common scenario of a single dacpac reference.
