### ISSUE TITLE
Unable to deploy dacpac with Active Directory Interactive Authentication

### ISSUE THREAD

**Issue by jalley3** [microsoft/DacFx#35]
I am attempting to deploy a dacpac to an Azure SQL Database using dacfx. 

This works fine for Active Directory Password and Active Directory Integrated, however it does not work for Active Directory Interactive.

When using this connection string: 

`Data Source=testval.database.windows.net;authentication=active directory interactive;user id=jacob.alley@testval.com`

and configuring my DacServices object like so: 

`var dacServiceInstance = new DacServices(connectionString); `

I get the following error: 

`Cannot find an authentication provider for 'ActiveDirectoryInteractive'`

After looking at the documentation, its clear that there is an overload for the controller that accepts an IUniversalAuthProvider instance. Looking online I see no classes that already implement this, so I decided to try and implement my own. It grabs the token and returns it in the `GetValidAccessToken()` method.

Now my call looks like this:

```
var authProvider = new AzureADAuth(connectionString);
                var dacServiceInstance = new DacServices(connectionString, authProvider);
```

When I run the deployment now, I am able to verify that my interface implementation is being called (by setting breakpoints), but after it returns the access token, it errors out with the following message:

`InvalidOperationException: Cannot set the AccessToken property if 'UserID', 'UID', 'Password', or 'PWD' has been specified in connection string.`

Ok so now I try and remove the username from the connection string before passing it in: 

```
var authProvider = new AzureADAuth(connectionString);
                var builder = new SqlConnectionStringBuilder(connectionString);
                builder.Remove("User Id");
                var dacServiceInstance = new DacServices(builder.ConnectionString.Replace("ActiveDirectoryInteractive", "Active Directory Interactive"), authProvider);
```

This time my interface does not even get called and it fails with this error, demanding that I provide a userid:

```
Cannot use 'Authentication=Active Directory Interactive' without 'User ID' or 'UID' connection string keywords.
```

So in one step it requires the UserID and the other it says that it cannot be used with the UserId provided...

Please help provide a working example of how to deploy to an Active Directory Interactive endpoint using DacFx. 

As a note, I am using the most up to date version of DacFX and also have the most recent version of System.Data.SqlClient installed as part of the project.

**Comment by jalley3** [comment]
Hi team, just following up as I am blocked on this, please assist.

**Comment by jalley3** [comment]
Does anyone check this?

**Comment by arvindshmicrosoft** [comment]
@dzsquared FYI and possible action.

@jalley3 I can take a quick look; do you have a complete sample to repro the issue? Also, I presume this is Windows? What version of .NET are you using? Does the standalone [sqlpackage](https://aka.ms/sqlpackage) utility work?

For time-sensitive matters it would always be a good idea to contact our support team, who are better placed to provide timely support. They will internally route as needed to the corresponding engg. teams.

**Comment by arvindshmicrosoft** [comment]
@jalley3 it would be really helpful if you provide your repro (without any sensitive info of course) and most importantly the versions of .NET and dependencies that you are using.

```csharp
            var connectionString = "Data Source=mylogicalserver.database.windows.net;authentication=active directory interactive;user id=myid@mydomain.com";
            var dacServiceInstance = new DacServices(connectionString);
            var dacpac = DacPackage.Load(@"sample.dacpac");
            var options = new DacDeployOptions();
            dacServiceInstance.Deploy(dacpac, "dacfxaad", options: options);
```

When the above is tested with:
* Microsoft.SqlServer.DacFx 160.5196.4-preview
* Windows 10 (10.0.19043.1237)

... it runs as designed wherein it pops up the authentication window in the browser, and when authentication is completed, the sample executes successfully. Please share your minimal repro with the environment so that we can isolate what is going on.

**Comment by jalley3** [comment]
Ugh, I had not tried the preview release, but it does seem to work with that, so thank you for the response! Any idea when the preview release will no longer be in preview?

**Comment by jalley3** [comment]
I think i was originally using the x64 variety so not sure if that was what was affecting it but like i said: 

```
When using this connection string:

Data Source=testval.database.windows.net;authentication=active directory interactive;user id=jacob.alley@testval.com

and configuring my DacServices object like so:

var dacServiceInstance = new DacServices(connectionString);

I get the following error:

Cannot find an authentication provider for 'ActiveDirectoryInteractive'
```

That was the error I got when using 150 version, as if it was expecting an authprovider to be passed into the DacServices constructor

**Comment by ErikEJ** [comment]
Use the .x64 version

**Comment by ErikEJ** [comment]
150 uses MDS as well. Why are you mentioning System.Data.SqlClient?

**Comment by jalley3** [comment]
In the post I just linked it says " Going forward, support for new SQL Server features will be implemented in Microsoft.Data.SqlClient." this makes me think that before 160, it was not using MDS, which is why i mentioned SDS...and the error message matches the error message i get when trying an Interactive authentication in SDS (And it doesnt work for 150 but DOES work for 160 using the exact same connection string).

**Comment by dzsquared** [comment]
As to the GA date for DacFx 160 this is expected by end of the year.

As to the initially reported issue, yes if you use DacFx in .NET framework 4.6 you will use SDS by default.  

Since this seems to be a greenfield project, is there consideration for using .NET core instead?  You would immediately have support for MDS in DacFx 150.   On .NET core I'm able to successfully execute the sample code above from @arvindshmicrosoft on DacFx 150.5164.1

**Comment by llali** [comment]
hi @jalley3, if you use sqlpackage executable, option /UniversalAuthentication more info [here](https://docs.microsoft.com/en-us/sql/tools/sqlpackage/sqlpackage-export?view=sql-server-ver15 )) can be used for universal Auth. as @dzsquared mentioned, Dacfx 160 GA release will be available be end of the year.

**Comment by ErikEJ** [comment]
@dzsquared could this be closed?
