### ISSUE TITLE
Ignore QueryInsights schema for extraction from Fabric DW

### ISSUE THREAD

**Issue by salilkanade** [microsoft/DacFx#357]
- SqlPackage or DacFx Version: 
- .NET Framework (Windows-only) or .NET Core:
- Environment (local platform and source/target platforms):

**Steps to Reproduce:**

1. Extract from a fabric DW
2. You get a 'queryinsights' schema extracted which is a system generated schema. It should be ignored from extraction

Here is the error message upon trying to build from the extracted project:

stdout: c:\sqlprojectfabric\DatabaseProjectsqldw01\queryinsights\Views\exec_requests_history.sql(1,277,1,277): Build error SQL71501: SqlComputedColumn: [queryinsights].[exec_requests_history].[status] contains an unresolved reference to an object. Either the object does not exist or the reference is ambiguous because it could refer to any of the following objects: [queryinsights].[fabric_query_completed].[query_status], [queryinsights].[fabric_query_completed].[t2]::[query_status] or [queryinsights].[fabric_query_starting].[t2]::[query_status].
 
stdout: c:\sqlprojectfabric\DatabaseProjectsqldw01\queryinsights\Views\exec_requests_history.sql(1,319,1,319): Build error SQL71501: SqlComputedColumn: [queryinsights].[exec_requests_history].[connection_id] contains an unresolved reference to an object. Either the object does not exist or the reference is ambiguous because it could refer to any of the following objects: [queryinsights].[fabric_query_completed].[t1]::[connection_id], [queryinsights].[fabric_query_starting].[connection_id] or [queryinsights].[fabric_query_starting].[t1]::[connection_id]. [c:\sqlprojectfabric\DatabaseProjectsqldw01\DatabaseProjectsqldw01.sqlproj]
    stdout: c:\sqlprojectfabric\DatabaseProjectsqldw01\queryinsights\Views\long_running_queries.sql(1,1409,1,1409): Build error SQL71501: SqlView: [queryinsights].[long_running_queries] has an unresolved reference to object [queryinsights].[fabric_query_starting].[statement]. [c:\sqlprojectfabric\DatabaseProjectsqldw01\DatabaseProjectsqldw01.sqlproj]
    stdout: c:\sqlprojectfabric\DatabaseProjectsqldw01\queryinsights\Views\long_running_queries.sql(1,1348,1,1348): Build error SQL71501: SqlView: [queryinsights].[long_running_queries] has an unresolved reference to object [queryinsights].[fabric_query_starting].[query_text_hash]. [c:\sqlprojectfabric\DatabaseProjectsqldw01\DatabaseProjectsqldw01.sqlproj]
    stdout: c:\sqlprojectfabric\DatabaseProjectsqldw01\queryinsights\Views\long_running_queries.sql(1,1386,1,1386): Build error SQL71501: SqlView: [queryinsights].[long_running_queries] has an unresolved reference to object [queryinsights].[fabric_query_starting].[session_id]. [c:\sqlprojectfabric\DatabaseProjectsqldw01\DatabaseProjectsqldw01.sqlproj]
    stdout: c:\sqlprojectfabric\DatabaseProjectsqldw01\queryinsights\Views\long_running_queries.sql(1,1461,1,1461): Build error SQL71501: SqlView: [queryinsights].[long_running_queries] has an unresolved reference to object [queryinsights].[fabric_query_starting].[batch_id]. [c:\sqlprojectfabric\DatabaseProjectsqldw01\DatabaseProjectsqldw01.sqlproj]
    stdout: c:\sqlprojectfabric\DatabaseProjectsqldw01\queryinsights\Views\long_running_queries.sql(1,1605,1,1605): Build error SQL71501: SqlView: [queryinsights].[long_running_queries] has an unresolved reference to object [queryinsights].[fabric_query_completed]. [c:\sqlprojectfabric\DatabaseProjectsqldw01\DatabaseProjectsqldw01.sqlproj]

**Comment by zijchen** [comment]
I don't think this is a DacFx issue. Those views aren't correctly marked as `is_ms_shipped` in `sys.all_views`. @salilkanade can you update/close this issue once you verify with the engine team?
