### ISSUE TITLE
Unable to start-up application with Microsoft.SqlServer.DacFX installed in .NET 5.  

### ISSUE THREAD

**Issue by hikarunoryoma** [microsoft/DacFx#36]
- DacFx Version: 150.5164.1
- .NET Framework (Windows-only) or .NET Core: .NET 5
- Environment (local platform and source/target platforms): x64 Microsoft Windows Server 2019 Standard -version 1809 OS build 17763.1098

**Steps to Reproduce:**

1. Starting an .NET 5 application with DacFX installed runs into an error on app start.  Error: ```Could not load file or assembly: The assembly may have been tampered with, or it was delay signed but not fully signed with the correct private key```
2. Current work around is to uninstall this library(and remove usages).  

**Did this occur in prior versions?  If not - which version(s) did it work in?**
When running in .NET Framework 472 things worked fine

**Comment by llali** [comment]
@zijchen is this the one you're looking at already?

**Comment by zijchen** [comment]
> @zijchen is this the one you're looking at already?

No I'm looking at #39 but they seem to be the same issue.

**Comment by llali** [comment]
close as duplicate #39
