### ISSUE TITLE
Custom Static Analysis Rules with DacFx 150 Not Executed on Build from VS 2022 Command Line

### ISSUE THREAD

**Issue by chlafreniere** [microsoft/DacFx#364]
Repro steps to be added subsequently 

**Steps to Reproduce:**

1. Create custom rules using older versions of dacfx (150) 
2. Copy the dlls to C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\Extensions\Microsoft\SQLDB\DAC\Extensions
3. Create a sqlproject with a script that won't be valid according to the rules you created
4. make sure <RunCodeAnalysis>True</RunCodeAnalysis> is set in the project
5. run "msbuild [your project].sqlproj /p:rebuild

Expected: Build should show the message from the custom rule as warning
Actual: There's no warning
**Did this occur in prior versions?  If not - which version(s) did it work in?**

(DacFx/SqlPackage/SSMS/Azure Data Studio)

**Comment by llali** [comment]
I verified building the same rules with DacFx 160, which is the one VS 2022 uses, fixes the problem. The reason that rules compiled with DacFx 150 cannot be loaded in VS 2022 is that MEF for some reason cannot match the types. Here's the debug message from MEF trying to load the custom rules: `The import requires metadata 'PlatformCompatibility' to be of type 'Microsoft.SqlServer.Dac.Extensibility.TSqlPlatformCompatibility' but the provided value 'All' is of type 'Microsoft.SqlServer.Dac.Extensibility.TSqlPlatformCompatibility'`

**Comment by llali** [comment]
as workaround, rebuild the custom rules using DacFx 160

**Comment by NathanMSFT** [comment]
@llali - This issue stems from a support case where we observed this issue with the custom rules (SqlServer.Rules) from https://github.com/tcartwright/SqlServer.Rules/releases. Are you suggesting that it's not a problem with VS 2022/SSDT, but the way the custom rules were built/compiled? I'm not familiar with this aspect of Custom Rules, so I'm requesting clarification. Is this something that the custom rules developer must do?

**Comment by chlafreniere** [comment]
Here are instructions that @llali created and I'm passing along for how to get the rules built in the SqlServer.Rules repo and get them to play nicely with VS 2022 (and its command-line equivalent):

- Clone [tcartwright/SqlServer.Rules: SQL Server static code analysis rules for SSDT database projects (github.com)](https://github.com/tcartwright/SqlServer.Rules)
- replace any version "150.5164.1" to "162.1.167". This is the dacfx version the project was using.
- there are some old packages that need to be updated to System.Runtime.CompilerServices.Unsafe to 6.0.0
- run msbuild /restore
- run msbuild
- get the dlls from git\SqlServer.Rules\SqlServer.Rules\bin\Debug\net472 and copy to C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\Extensions\Microsoft\SQLDB\DAC\Extensions\SqlServer.Rules
    - I cleaned everything in C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\Extensions\Microsoft\SQLDB\DAC\Extensions\SqlServer.Rules so now it only has these:

    ![image](https://github.com/microsoft/DacFx/assets/40371649/6ad3dd6c-9a6c-4ba1-9fac-4a330da61338)

    - Now if you run the build on SQL Project, you will see the rules are applied

Root cause appears to be that MEF has a problem with assembly version changes (150.x.x vs 160.x.x)

**Comment by NathanMSFT** [comment]
Thanks @chlafreniere and @llali for your work on this!!!

**Comment by llali** [comment]
as mentioned above this is by design. If the rules are compiled with DacFx 150, they cannot be used in a SQL project building with dacfx 160. Please compile the rules with latest version of dacfx. additional warnings are added to build diagnostic logs so user gets some information about why rules are not loaded
