### ISSUE TITLE
Add support "add column statement with 'with values' when nullable" deploy option

### ISSUE THREAD

**Issue by wesrivery** [microsoft/DacFx#38]
I'm always frustrated when add column with default values and is nullable.
I always modify a statement as below.

before
```sql
ALTER TABLE [dbo].[TableName]
    ADD [ColumnName] VARCHAR (1) DEFAULT ('0') NULL;
```

after 
```sql
ALTER TABLE [dbo].[TableName]
    ADD [ColumnName] VARCHAR (1) NULL DEFAULT ('0') WITH VALUES;
```

**Describe the solution you'd like**
Add deploy option that insert 'with values' to "ALTER TABLE ... ADD ..." statement.

**Comment by ssreerama** [comment]
@wesrivery Sorry for the delayed response, and Thank you for clear explanation with examples, very much appreciated and I'll get back to you with what my findings! Thanks.

**Comment by ssreerama** [comment]
This Issue has been fixed and will be available with the upcoming release of DacFx.

The syntax "WITH VALUES" for adding new column of NULL type to the existing table, the default constraint value will be going to update the rows of the new column. This can be done by the deployment option /p:GenerateSmartDefaults=true, default is false.
<html>
<body>


/p: | GenerateSmartDefaults=(BOOLEAN 'False') | 
-- | -- 



</body>
</html>
