### ISSUE TITLE
Build Error on CTAS Statements

### ISSUE THREAD

**Issue by joearusinfo** [microsoft/DacFx#406]
Type: <b>Bug</b>

I have a database project created for a datawarehouse in Microsoft Fabric. I have a CTAS statement within a stored procedure which is working in Fabric Datawarehouse but in SQL Database Project it throws build error.

Extension version: 1.3.1
Azure Data Studio version: azuredatastudio 1.46.0 (39449bbe88a0bc4092c9b205cad10d0a556beffd, 2023-09-16T01:40:10.706Z)
OS version: Windows_NT x64 10.0.22621
Restricted Mode: No
Preview Features: Enabled
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 x 2419)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.65GB (4.08GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by joearusinfo** [comment]
@dzsquared , Thanks for the update.

**Comment by NathanNZ** [comment]
@dzsquared is this still estimated for release by the end of spring? Or is this something that might fall into the next quarter?

**Comment by joearusinfo** [comment]
@ssreerama , glad it is fixed. so how can I apply it on Azure Data Studio? should I update any extension?

**Comment by ssreerama** [comment]
@joearusinfo , currently this fix can be seen in SqlPackage and DacFx only. You can see this in ADS with its upcoming release.
