### ISSUE TITLE
Build ouput seems to be badly formed, causing unexpected formatting of error list

### ISSUE THREAD

**Issue by ErikEJ** [microsoft/DacFx#415]
Build from a .sqlproj in VS 17.9.1:

```
C:\Code\Github\EFCorePowerTools\test\ScaffoldingTester\Database\dbo\Procedures\Procedure1.sql(1,24): Warning:  : SR0016 : Microsoft.Rules.Data : Stored procedure(sp_Procedure1) includes sp_ prefix in its name.
C:\Code\Github\EFCorePowerTools\test\ScaffoldingTester\Database\dbo\Procedures\Procedure1.sql(1,1): Warning:  : SRN0002 : SqlServer.Rules : Avoid 'sp_' prefix when naming stored procedures.
C:\Code\Github\EFCorePowerTools\test\ScaffoldingTester\Database\dbo\Procedures\Procedure1.sql(1,1): Warning:  : SRP0005 : SqlServer.Rules : SET NOCOUNT ON is recommended to be enabled in stored procedures and triggers.
C:\Code\Github\EFCorePowerTools\test\ScaffoldingTester\Database\dbo\Tables\Table1.sql(1,1): Warning:  : SRN0006 : SqlServer.Rules : Two part naming on objects is required.
C:\Code\Github\EFCorePowerTools\test\ScaffoldingTester\Database\dbo.DepartmentHistory(1,1): Warning:  : SRD0002 : SqlServer.Rules : Table does not have a primary key.
C:\Code\Github\EFCorePowerTools\test\ScaffoldingTester\Database\dbo.DepartmentHistory(12,1): Warning:  : SRN0007 : SqlServer.Rules : Index 'ix_DepartmentHistory' does not follow the company naming standard. Please use a format that starts with IX_DepartmentHistory*.
```
=> Error list:

![image](https://github.com/microsoft/DacFx/assets/4169187/dd892428-44a7-40a3-81aa-b669e3326b4d)

Build from some other tool:

```
1>C:\Code\Github\MSBuild.Sdk.SqlProj\test\TestProjectWithAnalyzers\Procedures\sp_Test.sql(4,12): warning SR0001: Microsoft.Rules.Data : The shape of the result set produced by a SELECT * statement will change if the underlying table or view structure changes.
1>C:\Code\Github\MSBuild.Sdk.SqlProj\test\TestProjectWithAnalyzers\Procedures\sp_Test.sql(1,24): warning SR0016: Microsoft.Rules.Data : Stored procedure(sp_Test) includes sp_ prefix in its name.
1>C:\Code\Github\MSBuild.Sdk.SqlProj\test\TestProjectWithAnalyzers\Procedures\sp_Test.sql(1,1): warning SRN0002: SqlServer.Rules : Avoid 'sp_' prefix when naming stored procedures.
1>C:\Code\Github\MSBuild.Sdk.SqlProj\test\TestProjectWithAnalyzers\Procedures\sp_Test.sql(1,1): warning SRP0005: SqlServer.Rules : SET NOCOUNT ON is recommended to be enabled in stored procedures and triggers.
```

=> [Better error list](https://github.com/rr-wfm/MSBuild.Sdk.SqlProj/pull/515#issuecomment-1964027916) (IMHO)

Seems to be cause by the multiple : signs here` Warning:  : SR0016 :`

[Docs](https://learn.microsoft.com/en-us/visualstudio/msbuild/msbuild-diagnostic-format-for-tasks?view=vs-2022)

**Comment by llali** [comment]
this might be a bug in SSDT instead of dacfx

**Comment by ErikEJ** [comment]
@llali agree, it is related to how SSDT reports  build results, not DacFX as such

**Comment by dzsquared** [comment]
While the bug surfaces in SSDT, it seems like its DacFx outputing build errors with the extra semicolon (between Warning: SR0016) on code analysis rules validation.  That's a DacFx item I would suggest we keep for future improvement.

**Comment by ErikEJ** [comment]
Looking forward.. Now, if only DacFX was open source 😅

**Comment by llali** [comment]
I have a fix for this in DacFx. Here's the output from dotnet build generated from my test after the fix:
`"StaticCodeAnalysis warning SR0001: Microsoft.Rules.Data : The shape of the result set produced by a SELECT * statement will change if the underlying table or view structure changes.",
"StaticCodeAnalysis warning SR0016: Microsoft.Rules.Data : Stored procedure(sp_Procedure1) includes sp_ prefix in its name.",
"warning SQL71502: Procedure: [dbo].[sp_Procedure1] has an unresolved reference to object [dbo].[InvalidTable]"`

**Comment by ErikEJ** [comment]
@llali Great news. I am surprised that DacFX actually generates the analysis output and nit SSDT. What is the timeline for the fix? VS 17.11??

**Comment by dzsquared** [comment]
@ErikEJ - yes, this change would first appear in a preview of a future (17.11) release of VS. I can't venture which preview just yet. :)
As I'm sure you guessed, it will not appear in 17.10.

kudos @llali for pinning the message anomaly down in dacfx

**Comment by dzsquared** [comment]
This landed in https://www.nuget.org/packages/Microsoft.SqlServer.DacFx/162.3.557-preview, not positive which 17.11 preview this will hit yet.

**Comment by llali** [comment]
fixed in 162.3

**Comment by ErikEJ** [comment]
@dzsquared Was this supposed to be fixed in 17.11 - I do not see it !?

**Comment by dzsquared** [comment]
argh - 17.11 shipped with DacFx 162.2.127

**Comment by ErikEJ** [comment]
Nooooo.. why is it so far behind??

**Comment by ErikEJ** [comment]
So what VS version will have 162.3??

**Comment by ErikEJ** [comment]
VS 17.12 preview 2 - still broken @dzsquared @llali - is that expected?

![image](https://github.com/user-attachments/assets/fc81462c-9c1e-4006-a6f8-051f2c420ad2)

**Comment by ErikEJ** [comment]
At least it works with .sqlprojx:

1>C:\Users\..\source\repos\Database2\Database2\Table1.sql(1,1,1,1): StaticCodeAnalysis warning SRN0006: SqlServer.Rules : Two part naming on objects is required.
1>C:\Users\..\source\repos\Database2\Database2\Table1.sql(1,1,1,1): StaticCodeAnalysis warning SRN0007: SqlServer.Rules : PrimaryKeyConstraint found without a name.

![image](https://github.com/user-attachments/assets/567b807c-5720-4314-8222-01bd24be7c7c)
