### ISSUE TITLE
Possible to get release notes for current packages? <EOM> 

### ISSUE THREAD

**Issue by ErikEJ** [microsoft/DacFx#42]

**Comment by ErikEJ** [comment]
If there was just some way to automate that??

**Comment by dzsquared** [comment]
@ErikEJ we do automate pulling changesets - but there's still an element of cleanup and checking for potentially sensitive info.

however! we are adding release notes on the nuget now: https://www.nuget.org/packages/Microsoft.SqlServer.DacFx/160.5323.3-preview. (started with a full dump of all v160 items)
