### ISSUE TITLE
Adding existing project causes VS 2022 to hang

### ISSUE THREAD

**Issue by jphellemons** [microsoft/DacFx#425]
- SqlPackage or DacFx Version:
- .NET Framework (Windows-only) or .NET Core: 8.0.200
- Environment (local platform and source/target platforms): local

**Steps to Reproduce:**

1. dotnet new -i Microsoft.Build.Sql.Templates
2. dotnet new sqlproj -n ProductsTutorial
3. create table (optional)
4. Open VS 2022 Version 17.9.2
5. Right click in solution
6. Add existing project
7. select sqlproj
8. hang/wait

**Did this occur in prior versions?  If not - which version(s) did it work in?**
idk, first time I am using the new sdk database project

**Comment by dzsquared** [comment]
closing this as we have several items tracking the work for SSDT to support Microsoft.Build.Sql projects.

https://github.com/microsoft/DacFx/issues/180#issuecomment-1332850284

**Comment by RyanThomas73** [comment]
@jphellemons I encountered the problem you described yesterday and the following allowed me to work around it:

After your step 2 and before opening visual studio, perform a `dotnet restore` on the new .sqlproj from the command line.
