### ISSUE TITLE
*** The SourceFile argument must refer to a file with a '.bacpac' extension.

### ISSUE THREAD

**Issue by jackliusr** [microsoft/DacFx#428]
- SqlPackage or DacFx Version:  162.2.111.2
- .NET Framework (Windows-only) or .NET Core: Microsoft.AspNetCore.App 8.0.2
- Environment (local platform and source/target platforms): wsl2+ubuntu22.04

**Steps to Reproduce:**

1. use sqlpackage to install a .dacpac file.

**Did this occur in prior versions?  If not - which version(s) did it work in?**
It is my first time to use it in this environment.

**Comment by dzsquared** [comment]
Hi @jackliusr - can you share an example of the command you're trying to run with SqlPackage?

There's 2 pairs of commands:
1. import/export for bacpac files
2. publish/extract for dacpac files


If you have a dacpac file - you want to use [**publish**](https://learn.microsoft.com/en-us/sql/tools/sqlpackage/sqlpackage-publish?view=sql-server-ver16) to apply that dacpac to a new or existing database.

**Comment by jackliusr** [comment]
I use "publish" command now. however, I got the following error:  I use "  /TargetConnectionString:"Server=:::,1433;....". I tried "Server=localhost,1433;" ,"Server=localhost,1433;" etc. All the connection strings work in azure data studio in wsl.

`*** A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 35 - An internal exception was caught)
*** A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 35 - An internal exception was caught)`

**Comment by llali** [comment]
@jackliusr the error above happens when commenting to the server fails. You can verify you connection string using SSMS before calling a publish command. The error "The SourceFile argument must refer to a file with a '.bacpac' extension" only happens if calling sqlpackag with /a:import parameter.

**Comment by jackliusr** [comment]
@llali , you are right.  I used publish command after @dzsquared replied. However, I got connection string issue. The connection string is definitely right, as I used it for as connection string in another parts which work.

For the connection issue, it might not be relevant to this issue considering the issue about file name. 

Should I close this issue?
