### ISSUE TITLE
Support dotnet publish

### ISSUE THREAD

**Issue by benjamin-hodgson** [microsoft/DacFx#447]
My sqlproj looks like this

```xml
<Project Sdk="Microsoft.Build.Sql/0.1.15-preview">

    <PropertyGroup>
        <Name>MyDb</Name>
        <DSP>Microsoft.Data.Tools.Schema.Sql.Sql160DatabaseSchemaProvider</DSP>
        <ModelCollation>1033, CI</ModelCollation>
    </PropertyGroup>

</Project>
```

I'd like to publish the output `dacpac` to a folder (along with my other projects) for deployment. Using `dotnet publish` throws an error:

```
C:\Program Files\dotnet\sdk\8.0.205\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(164,5): error MSB4036: 
 The "AllowEmptyTelemetry" task was not found. Check the following: 1.) The name of the task in the project file is the 
 same as the name of the task class. 2.) The task class is "public" and implements the Microsoft.Build.Framework.ITask  
interface. 3.) The task is correctly declared with <UsingTask> in the project file, or in the *.tasks files located in  
the "C:\Program Files\dotnet\sdk\8.0.205" directory. [D:\test\MyDb\MyDb.sqlproj]
```

**Comment by dzsquared** [comment]
Our current proposal for `dotnet publish` functionality will diverge from the SSDT and original SQL projects msbuild publish capability and I believe aligns with the behavior you expected.  The original SQL projects initiate a DacFx publish operation of the build artifact to a database connection specified in a publish profile. With Microsoft.Build.Sql the plan to align with the default dotnet publish behavior.

https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-publish
> dotnet publish compiles the application, reads through its dependencies specified in the project file, and publishes the resulting set of files to a directory.

The dacpac is the build artifact from a Microsoft.Build.Sql project that would be published/copied to the directory.

Applying this dacpac to a database would require the sqlpackage dotnet tool (or another implementation of DacFx publish APIs)

**Comment by benjamin-hodgson** [comment]
Great to hear - that's exactly what I was hoping you'd say! :)

**Comment by srbrills** [comment]
Is there any information on when this behavior is expected to be implemented?  Glad to hear about the publish functionality to a directory.

**Comment by ErikEJ** [comment]
@srbrills How is that very different from getting the build output?

**Comment by srbrills** [comment]
It is not very different, true.  I currently just get the build output.  However, it keeps me from being able to use a simpler set of automation tasks in a pipeline.  It would be great if I could just run `dotnet publish` against each of the projects in a solution, making a build pipeline more simplified, but as it stands now I have to write an extra conditional step for these newer SQL projects.

**Comment by BrianVallelunga** [comment]
I just came to look for the same behavior. I'd like to use dotnet publish to put the dacpac file into an output folder, along with any scripts, similar to how it works with out projects.
