### ISSUE TITLE
Allow excluding Sensitivity Classifications from schema comparisons

### ISSUE THREAD

**Issue by tmenier** [microsoft/DacFx#46]
One of our cloud engineers recently started adding [sensitivity classifications ](https://docs.microsoft.com/en-us/sql/relational-databases/security/sql-data-discovery-and-classification)to columns in our Azure SQL database, via the Azure portal. We're using DacFx for schema updates as part of our automated release process, and these are getting dropped:

```
DROP SENSITIVITY CLASSIFICATION FROM
    [dbo].[MyTable].[MyColumn];
```

This makes sense since these exist in the target and not the source, but ideally we'd to just ignore them so that security/ops people are free to add them independent of our code release cycles. But I'm struggling to figure out how to do this with the [options](https://docs.microsoft.com/en-us/dotnet/api/microsoft.sqlserver.dac.dacdeployoptions) available. My understanding is that these are extended properties, but none of these work:

```
opts.DropExtendedPropertiesNotInSource = false;
opts.IgnoreExtendedProperties = true;
opts.ExcludeObjectTypes = new[] {ObjectType.ExtendedProperties , ...};
```

After much experimenting, it seems that excluding `ObjectType.Tables` is the only thing that works, but unfortunately that will also exclude just about everything we want included. Am I correct that DacFx simply doesn't support excluding these?

As a side note, where can I find the DacFx source? Or is it not open source?

**Comment by zijchen** [comment]
@tmenier [Microsoft.SqlServer.DacFx 160.6161.0](https://www.nuget.org/packages/Microsoft.SqlServer.DacFx/160.6161.0) was released yesterday. We introduced an `IgnoreSensitivityClassifications` DacDeployOption that should exclude sensitivity classifications from deployment, can you give it a try?
