### ISSUE TITLE
Visual Studio throws critical error when UDT type has index

### ISSUE THREAD

**Issue by ssreerama** [microsoft/DacFx#464]
- SqlPackage or DacFx Version: Both
- .NET Framework (Windows-only) or .NET Core: Both
- Environment (local platform and source/target platforms):

**Steps to Reproduce:**

1. Create a DB project and add a User defined table type
2. Add a inline index to it
3. Once the index is added, VS is struck with a critical error window

**Did this occur in prior versions?  If not - which version(s) did it work in?**

(DacFx/SqlPackage/SSMS/Azure Data Studio)

**Comment by ErikEJ** [comment]
Which VS version??
