### ISSUE TITLE
Unclarity on system .dacpacs

### ISSUE THREAD

**Issue by ErikEJ** [microsoft/DacFx#466]
There are a number of non deprecated package versions published for each engine edition here: https://www.nuget.org/packages/Microsoft.SqlServer.Dacpacs.Master#versions-body-tab

Is the advise to always use the latest version? If so, maybe consider deprecating the older versions so consumers become aware of the updates?

**Comment by dzsquared** [comment]
Non-formalized advice is to use the latest version that aligns with the version of SQL, there are 7 versions of SQL associated with the system dacpacs

![image](https://github.com/microsoft/DacFx/assets/12227241/6e0c8b31-3eef-4f91-aa04-333b27d421d0)


Tagging this to documentation for my backlog so this gets better captured, will likely deprecate the handful of "aged out" versions.

**Comment by dzsquared** [comment]
fyi @zijchen

**Comment by ErikEJ** [comment]
Thanks, I will add this to the MsBuild.SDK.SqlProj docs  as a user had issues with an older package version (master 150.0.0)

**Comment by dzsquared** [comment]
included here - https://learn.microsoft.com/en-us/sql/tools/sql-database-projects/concepts/package-references?view=sql-server-ver16&pivots=sq1-visual-studio#system-databases
