### ISSUE TITLE
Binskim errors in SqlServerSpatial160.dll

### ISSUE THREAD

**Issue by dhavv** [microsoft/DacFx#473]
**Is your feature request related to a problem? Please describe.**
I'm trying to address [Binskim](https://github.com/microsoft/binskim) issues from my webapp. I noticed SqlServerSpatial160.dll fails on [EnableControlFlowGuard](https://github.com/microsoft/binskim/blob/main/docs/BinSkimRules.md#rule-ba2008enablecontrolflowguard) rule. I am not sure if this is fixable since this seems to be from Microsoft.SqlServer.Types dependency?

**Describe the solution you'd like**
Binskim `EnableControlFlowGuard` rule passed

**Describe alternatives you've considered**

**Additional context**

**Comment by zijchen** [comment]
Hi @dhavv please contact the owners of Microsoft.SqlServer.Types directly. You can use the "Contact Owners" link from the Nuget page: https://www.nuget.org/packages/Microsoft.SqlServer.Types
