### ISSUE TITLE
Bacpac file won't restore due to columnstore indexes on columns with specific data types.

### ISSUE THREAD

**Issue by dzsquared** [microsoft/DacFx#475]
from https://feedback.azure.com/d365community/idea/c7ea15d6-364b-ef11-b4ac-000d3a7b1c7e

Situation:
We are using Serverless Azure SQL Databases as projects. Afterwards we delete these databases but before we do that we create backups of the databases. We are using SqlPackage.exe (version: 162.3.566) to create bacpac files.
Restoring bacpac files back to our Azure subscription works fine, except for following situations:
When a database contains a clustered columnstore index on a table that contains following datatypes: varchar(max) , nvarchar(max), or varbinary
in this situation we can successful create bacpacs but we are NOT able to restore the bacpacs. It gives following errors:
Error SQL72014: Framework Microsoft SqlClient Data Provider: Msg 1919, Level 16, State 1, Line 1 Column 'vcharmax' in table 'dbo.Table_ColumnstoreIndex_01' is of a type that is invalid for use as a key column in an index.
Error SQL72045: Script execution error.  The executed script:
CREATE CLUSTERED INDEX [CCI_Table_ColumnstoreIndex_01]
    ON [dbo].[Table_ColumnstoreIndex_01]([vcharmax]);
CREATE CLUSTERED COLUMNSTORE INDEX [CCI_Table_ColumnstoreIndex_01]
    ON [dbo].[Table_ColumnstoreIndex_01] WITH (DROP_EXISTING = ON);
The same error appears when using nvarchar(max) and varbinary.
 
It seems that something goes wrong on the tool side when the BACPAC is created or restored. This statement:
CREATE CLUSTERED INDEX [CCI_Table_ColumnstoreIndex_01]     ON [dbo].[Table_ColumnstoreIndex_01]([vcharmax]);
should not be there. Since the data type varchar(MAX) is not supported for rowstore clustered index, this statement gives an error. But would the data type be a supported one, the next statement to create the clustered columnstore index would fail, since you can only have one clustered index on a table.
In my opinion the restore statement should be plain and simple:
CREATE CLUSTERED COLUMNSTORE INDEX [CCI_Table_ColumnstoreIndex_01] ON [dbo].[Table_ColumnstoreIndex_01]
 
I understand that we should prevent making clustered columnstore indexes on these kind of columns, but why is it in the first place allowed to make these indexes that gives us issues in our restoring process of BACPAC files.
 
Anyone experiencing the same issues or know how to fix this problem?
 
BTW: This cmd is used at restoring the bacpac,:
SqlPackage /Action:Import /SourceFile:"F:\db\bacpacs\restoretestdb01.bacpac" /UniversalAuthentication:True /TargetConnectionString:"Server=tcp:servername.database.windows.net,1433;Initial Catalog=restoretestdb01;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=90;"

**Comment by MarkieMark73** [comment]
Hi Drew, Did you hear any updates on the bug report. And if it is planned to be fixed in upcoming releases?
Thanks in advance!

**Comment by abhikum** [comment]
@MarkieMark73 Can you provide a **simplified** version of the [dbo].[Table_ColumnstoreIndex_01] schema to help reproduce the issue? I want to ensure I am not overlooking anything while addressing this issue.

**Comment by MarkieMark73** [comment]
@abhikum 

[test-script.txt](https://github.com/user-attachments/files/17588240/test-script.txt)

I tested 4 data types in the clustered columnstore indexes (see attachment)

1. [Table_ColumnstoreIndex_01] --> varchar(max) --> restore failed
2. [Table_ColumnstoreIndex_02] --> nvarchar(max) --> restore failed
3. [Table_ColumnstoreIndex_03] --> varbinary(max) --> restore failed
4. [Table_ColumnstoreIndex_04] --> uniqueidentifier --> restore succeeded

See second attachment the error messages:
[error-messages.txt](https://github.com/user-attachments/files/17588313/error-messages.txt)

Hope this makes sense. Let me know if this is sufficient for you for testing.
Kind regards,
Mark

**Comment by MarkieMark73** [comment]
> [@MarkieMark73](https://github.com/MarkieMark73) Can you provide a **simplified** version of the [dbo].[Table_ColumnstoreIndex_01] schema to help reproduce the issue? I want to ensure I am not overlooking anything while addressing this issue.

Hi @abhikum ,

See reply, don't hesitate to ask me more.

Thanks,
Mark

**Comment by abhikum** [comment]
@MarkieMark73 -- Yes, that is correct. If the first column supports a clustered index, then the restore will complete successfully. Please inform me if this is not the case.

It may not be apparent to users that DacFx needs to create a temporary clustered index before creating a clustered columnstore index during restoration. As part of the fix, DacFx will select a column with a supported type instead of the first column.
Hope it answers your question.

**Comment by abhikum** [comment]
This issue was fixed in 162.5.57 https://learn.microsoft.com/en-us/sql/tools/sqlpackage/release-notes-sqlpackage?view=sql-server-ver16#162557-sqlpackage
