### ISSUE TITLE
Azure SQL - JSON Data Type

### ISSUE THREAD

**Issue by rac146** [microsoft/DacFx#477]
- SqlPackage or DacFx Version: 1.62.3.566.1
- Microsoft.SqlServer.Dacpacs.Azure.Master: 160.2.2
- .NET Framework (Windows-only) or .NET Core: .NET Core
- Environment (local platform and source/target platforms): Local

For Azure SQL Platform type, trying to build a sqlproj with a JSON data type, but receiving a SQL71501 error - "has an unresolved reference to Built-in type [dbo].[JSON]." Now that JSON is in preview for Azure SQL, can this be added so these projects build successfully?

**Comment by dzsquared** [comment]
![image](https://github.com/user-attachments/assets/f840b729-ebf4-46b2-9753-837b3ecbec4e)

**Comment by dzsquared** [comment]
JSON type support is on the way in DacFx/sqlproj

ex) https://www.nuget.org/packages/Microsoft.SqlServer.DacFx/162.4.28-preview#releasenotes-body-tab

**Comment by rac146** [comment]
Awesome, thanks!

Is there a way to reference that preview version for a "sqlproj" in Azure Data Studio/VS Code? Or do those other packages need to be updated eventually as well? (I'm a little confused on how all the packages relate to one-another)

I tried installing the version of 162.4.28-preview via dotnet install -g but it still didn't build the sqlproj.

sqlproj config:
![image](https://github.com/user-attachments/assets/f7d6e9b4-0ae6-4580-95d7-885530b5e6f3)

**Comment by dzsquared** [comment]
it isn't there quite yet on the sqlproj side. you could take the Microsoft.Build.Sql code from this repo and build it yourself from the DacFx 162.4 preview (and you are certainly welcome to), but that's not realistic fix as we need to get support for JSON type shipped.

I'll check in on the completeness of the JSON work in dacfx before throwing out any kind of timeline for Microsoft.Build.Sql getting released with it included

**Comment by rac146** [comment]
I'll wait for the release! Thanks again..

**Comment by dzsquared** [comment]
To be clear - building a SQL project with the JSON type will require the next version of Microsoft.Build.Sql (likely 0.2.1-preview) with the latest dacfx release
