### ISSUE TITLE
Rules not being picked up by 0.2.3

### ISSUE THREAD

**Issue by ErikEJ** [microsoft/DacFx#495]
- SqlPackage or DacFx Version: 162.4
- .NET Framework (Windows-only) or .NET Core:
- Environment (local platform and source/target platforms): Microsoft.Build.Sql 0.2.3 

**Steps to Reproduce:**

1. Add package ref to third party rules package
2. Build does not report errors from 3rd party package

**Did this occur in prior versions?  If not - which version(s) did it work in?**

(DacFx/SqlPackage/SSMS/Azure Data Studio)

**Comment by ErikEJ** [comment]
But maybe 0.2.3 does not include that?

**Comment by ErikEJ** [comment]
It does not. I wish the release proces / release notes were more transparent.

**Comment by zijchen** [comment]
Hi @ErikEJ yeah we're working on having the SDK release notes on GitHub. Which package are you trying to use? We currently support analyzer packages that are built using the C# way with analyzers in `analyzers/dotnet/cs`

**Comment by ErikEJ** [comment]
@zijchen Does 0.2.3 support analyzer packages??

I am using my own package and the files are in the correct location

**Comment by zijchen** [comment]
0.2.3 should support it, I just verified it locally as well. Do you mind sharing your binlog file?

**Comment by ErikEJ** [comment]
I am testing with an updated .sqlprojx. Let me do a simpler test in ADS.

**Comment by zijchen** [comment]
Sounds good, let us know your findings. Also, make sure you have `<RunSqlCodeAnalysis>true</RunSqlCodeAnalysis>` in your project, it's easy to miss.

If everything's working correctly, you should see the analyzer assembly added during the `ResolveLockFileAnalyzers` target in the binlog 
![image](https://github.com/user-attachments/assets/e6736e54-6f92-4dc1-9522-edb7750cf24f)

**Comment by ErikEJ** [comment]
@zijchen A plain `dotnet build` in ADS (no .sqlprojx involvement) works as expected! 🎉 

Guess .sqlprojx needs the latest DacFX somwhere?

```
<?xml version="1.0" encoding="utf-8"?>
<Project DefaultTargets="Build">
  <Sdk Name="Microsoft.Build.Sql" Version="0.2.3-preview" />
  <PropertyGroup>
    <Name>TestCA</Name>
    <ProjectGuid>{F6384BD0-0462-45C9-90FF-80BF08AB39CA}</ProjectGuid>
    <DSP>Microsoft.Data.Tools.Schema.Sql.Sql160DatabaseSchemaProvider</DSP>
    <ModelCollation>1033, CI</ModelCollation>
    <RunSqlCodeAnalysis>true</RunSqlCodeAnalysis>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="ErikEJ.DacFX.SqlServer.Rules" Version="1.1.0" />
    <PackageReference Include="ErikEJ.DacFX.TSQLSmellSCA" Version="1.1.0" />
  </ItemGroup>
</Project>
```
