### ISSUE TITLE
Microsoft.Build.Sql 0.2.4-preview throws error in VS 17.12 and MSBuild, works in dotnet build

### ISSUE THREAD

**Issue by czb182** [microsoft/DacFx#518]
VS2022 17.11.5

Microsoft.Build.SQL 0.2.4-preview

Can not load Database project, as this error is thrown.

 error  : The result "" of evaluating the value "$(MicrosoftNETBuildTasksAssembly)" of the "AssemblyFile" attribute in element <UsingTask> is not valid.  C:\Users\username\.nuget\packages\microsoft.build.sql\0.2.4-preview\Sdk\Sdk.targets

This is not happening with 0.2.3-preview

**Comment by zijchen** [comment]
What happens if you use `dotnet build `to build the project? Trying to see if this is a VS issue or otherwise

**Comment by akdanz** [comment]
This error only pops up in VS2022 (v17.11.5) for me, no issues with `dotnet build`.

**Comment by ErikEJ** [comment]
@akdanz You need to use .sqlprojx (SDK style SSDT) in VS 17.12 preview for proper MsBuild.Sdk.Sqlproj support. Pure luck if it works with VS 17.11

**Comment by ErikEJ** [comment]
@avivanoff it was never supported.. it is in 17.12 now

**Comment by czb182** [comment]
I just installed the VS 17.12 final release.  When i installed the SQL sdk project preview it did not let me open up existing .sqlproj database project(The application which this project type is based on was not found. Please try this link for further information: 00d1a9c2-b5f0-4af3-8072-f6c62b433612).  I would have assumed it would support .sqlproj for old format and support sdk style in .sqlprojx

**Comment by ErikEJ** [comment]
@czb182 It is either or at the moment, sadly!

**Comment by avivanoff** [comment]
> [@avivanoff](https://github.com/avivanoff) it was never supported.. it is in 17.12 now

@ErikEJ, I am completely confused now. What was not supported? Using Microsoft.Build.Sql SDK with Visual Studio and MSBuild builds?

All I know is that after upgrading to 17.12 I cannot use some of our non-SDK-style SQL projects like @czb182 reported, and I cannot update SDK-style SQL projects to 0.2.4-preview.

Are you going to fix/support building Microsoft.Build.Sql SDK projects with Visual Studio and MSBuild?

**Comment by avivanoff** [comment]
> I just installed the VS 17.12 final release. When i installed the SQL sdk project preview it did not let me open up existing .sqlproj database project(The application which this project type is based on was not found. Please try this link for further information: 00d1a9c2-b5f0-4af3-8072-f6c62b433612). I would have assumed it would support .sqlproj for old format and support sdk style in .sqlprojx

Make sure you do not have "SQL Server Data Tools" and "SQL Server Data Tools SDK-Style (Preview)" installed at the same time, see https://developercommunity.visualstudio.com/t/Trying-to-load-SSDT-projects-is-failing/10772324#T-ND10789149.

**Comment by dzsquared** [comment]
@cbz182 there's a lot of discussion on this thread already - is the recap that the 0.2.4-preview of the SDK isn't working with VS 2022 17.12, only 0.2.3-preview?

**Comment by avivanoff** [comment]
I think it is more of "0.2.4-preview of the SDK isn't working with any version of Visual Studio or MSBuild, only dotnet builds".

**Comment by dzsquared** [comment]
thanks - I've updated the title and we're digging into the issue.

as to @czb182's concern that we keep this moving and go as quick as possible with SDK-style projects in VS - there's a lot of complexity to SQL projects (schema compare, object explorer integration) and an additional layer of other VS components with dependencies into SSDT that we're navigating. We're pressing forward with support in VS.

**Comment by biltongza** [comment]
It's a bit of a farce to say the new SDK style projects are supported in 17.12, when you have to install the preview of SSDT, and remove the stable version, which causes this:
![Image](https://github.com/user-attachments/assets/40f3937d-0eaf-4abe-aad1-350a77458c94)

So effectively I can't use this because it means I kill the rest of the functionality I depend on in VS.

**Comment by ErikEJ** [comment]
@biltongza To enable SSDT SDK style, have both checkboxes checked (I only have Classic SQL projects enabled below):

![Image](https://github.com/user-attachments/assets/917c1c30-3dbb-4d3b-aa38-21cabe884ae8)

**Comment by biltongza** [comment]
@ErikEJ as mentioned by @avivanoff that doesn't seem to be a good idea according to MSFT 
> make sure you do not have "SQL Server Data Tools" and "SQL Server Data Tools SDK-Style (Preview)" installed at the same time, see https://developercommunity.visualstudio.com/t/Trying-to-load-SSDT-projects-is-failing/10772324#T-ND10789149.

**Comment by ErikEJ** [comment]
@biltongza Then those docs are wrong,sadly, this is my vs preview instance, that only works with SDK style projects:

![Image](https://github.com/user-attachments/assets/e12c7a56-2adc-4fce-9a5d-28b72336c468)

**Comment by avivanoff** [comment]
@zijchen, you closed this issue as completed, but there is no new NuGet package yet.
