### ISSUE TITLE
Error SQL71626: The element 'xyz' is not supported in Microsoft Azure SQL Database v12

### ISSUE THREAD

**Issue by klacol** [microsoft/DacFx#526]
- SqlPackage Version: 162.4.92.3
- .NET Framework (Windows-only) or .NET Core: 8.0
- Environment (local platform and source/target platforms): local, Windows 11, SQL Server 2022

**Steps to Reproduce:**

1. I try to export the structure of an OnPrem Database from SQL Server 2022 with SqlPackage to a bacpac file (see my cmd below)
2. I get the message "Error SQL71626: The element 'xyz' is not supported in Microsoft Azure SQL Database v12."
3. The bacpac file is not created

```shell
SqlPackage /Action:Export `
           /SourceConnectionString:"Server=tcp:SERVER,1433;Initial Catalog=DATABASE;Integrated Security=True;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=True;Connection Timeout=30;" `
           /TargetFile:"DATABASE.bacpac" `
           /p:VerifyExtraction=False
```

I cannot delete the element in the source database, since I need it in my database. Does this mean, that SqlPackage can only be used to manage Azure-Databases, and not "OnPrem-only" databases?

Is there another solution to manage the deployment of OnPrem-Databases?

Thanks for any hint in advance.

**Comment by ErikEJ** [comment]
@klacol For schema extraction, you should use the `/Action:Extract` action, not Export

**Comment by klacol** [comment]
Aahhh, my fault. this works:

```shell
SqlPackage /Action:Extract`
           /SourceConnectionString:"Server=tcp:SERVER,1433;Initial Catalog=DATABASE;Integrated Security=True;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=True;Connection Timeout=30;" `
           /TargetFile:"DATABASE.dacpac" 
```

Thank you!
