### ISSUE TITLE
Export fails with error - SQL71623: Model translation is not allowed because the model contains 1 errors

### ISSUE THREAD

**Issue by zijchen** [microsoft/DacFx#53]
Export fails when stored procedure contains DDL that references a user-defined function. Workaround is to use SqlPackage Extract action with `/p:ExtractAllTableData=true`.

- SqlPackage or DacFx Version: 15.0.5282.3
- .NET Framework (Windows-only) or .NET Core: .NET Core
- Environment (local platform and source/target platforms): SQL 2019 & Azure

**Steps to Reproduce:**

1. Create database with following schema
```tsql
CREATE FUNCTION [dbo].[Function1]()
RETURNS INT
AS
BEGIN

RETURN 1
    
END
GO

CREATE TABLE [dbo].[Table1](
	[DateCol] [date] NOT NULL,
	[FuncCol] [int] NOT NULL DEFAULT (CONVERT(INT, [dbo].[Function1]())),
) ON [PRIMARY]
GO

CREATE PROCEDURE [dbo].[Procedure1]
AS
BEGIN
	
	CREATE TABLE [dbo].Table1(
		[DateCol] [date] NOT NULL,
		[FuncCol] [int] NOT NULL DEFAULT (CONVERT(INT, [dbo].[Function1]())),
	);

END
GO
```
2. Export will fail with following error:
![image](https://user-images.githubusercontent.com/13544267/141832728-7706cf53-0dc7-4fa8-981e-0feaf81600fa.png)

**Comment by llali** [comment]
@zijchen didn't you already fix this?

**Comment by zijchen** [comment]
@llali no I recall working on this and verifying that it's reproducible, but don't think a fix was implemented yet.
