### ISSUE TITLE
Element or Annotation SqlIndex does not have Property Online

### ISSUE THREAD

**Issue by IVNSTN** [microsoft/DacFx#531]
- SqlPackage or DacFx Version: 162.5.57.1
  - sqlpackage /version: 15.0.5472.2
- .NET Framework (Windows-only) or .NET Core:
- Environment (local platform and source/target platforms): 
  - win 10 x64
  - SqlServer 2019
  - SSDT-style project
  - VS Build Tools 2022
  - msbuild 17.6.3

**Steps to Reproduce:**

1. build sqlproj with VS 2022 build tools
2. run `sqlpackage.exe /action:deployreport` (the first thing i've tried to test 162.5 update) for this dacpac

Log with the error:
```
Microsoft.Data.Tools.Diagnostics.Tracer Information: 25 : 2024-11-26T11:54:22 : Perf: Operation started (name, details): LoadTypes,
Microsoft.Data.Tools.Diagnostics.Tracer Verbose: 1 : 2024-11-26T11:54:22 : Entering ExtensionTypeLoader.LoadTypes().
Microsoft.Data.Tools.Diagnostics.Tracer Information: 25 : 2024-11-26T11:54:23 : Perf: Operation ended (name, details, elapsed in ms): LoadTypes,,166
Microsoft.Data.Tools.Diagnostics.Tracer Information: 25 : 2024-11-26T11:54:24 : Perf: Operation started (name, details): DeserializeXml,
Microsoft.Data.Tools.Diagnostics.Tracer Information: 25 : 2024-11-26T11:54:34 : Perf: Operation ended (name, details, elapsed in ms): DeserializeXml,,10045
Microsoft.Data.Tools.Diagnostics.Tracer Error: 19 : 2024-11-26T11:54:34 : Microsoft.SqlServer.Dac.DacServicesException:
Microsoft.Data.Tools.Schema.Sql.Deployment.DeploymentFailedException: The Element or Annotation class SqlIndex does not contain the Property class Online.
```

Seems to be related to #427 and feels like a backward incompatible change.

**Did this occur in prior versions?  If not - which version(s) did it work in?**

The same dacpac can be successfully used with dacfx 162.4.92.3 and sqlpackage /version 15.0.5472.2

(DacFx/SqlPackage/SSMS/Azure Data Studio)

**Comment by ErikEJ** [comment]
@IVNSTN - looks like an old sqlpackage.exe, so this seems expected:

I downloaded the Windows .zip file from here: https://learn.microsoft.com/en-us/sql/tools/sqlpackage/sqlpackage-download?view=sql-server-ver16
 
```
.\sqlpackage.exe /version
162.5.57.1
```

**Comment by IVNSTN** [comment]
Yes, sorry, it was sqlpackage from PATH, not from the folder I expected.
