### ISSUE TITLE
SqlPackage.exe fails to deploy updates when Graph tables use Partition functions with leading zeros. 

### ISSUE THREAD

**Issue by JerryNixon** [microsoft/DacFx#77]
- SqlPackage or DacFx Version: VISUAL STUDIO 2022 SQL Data Tools 17.0.62110.20190
- .NET Framework (Windows-only) or .NET Core: Framework
- Environment (local platform and source/target platforms): LocalDB (2019) & Azure SQL DB

Hi there SqlPackage.exe team,

I would like to report a bug in `SqlPackage.exe`. First deployment works fine, but subsequent deployments fail when there is a Graph table (Node or Edge) with a Partition Scheme using a Partition Function with INTEGER boundary values that have leading zeros in the function definition: `001, 002, 003`. This is VERY reproduceable. 

**Note: In non-Graph tables, leading zeros work fine.** 

Here’s the error (on the second (update) deployment): 

**One thing I want to share is that this vague error message took us DAYS to debug.** 

Here’s the repro script (remember you have to deploy it at least two times): 

````sql

GO
CREATE TABLE [dbo].Sample
(Id INT, PartitionKey AS Id % 2 PERSISTED) AS EDGE; -- ALSO NODE

GO
CREATE CLUSTERED INDEX Manages_PartitionIndex
  ON [dbo].Sample (PartitionKey)
  ON OddEven_PartitionScheme (PartitionKey);

GO
CREATE PARTITION FUNCTION OddEven_PartitionFunction (INT)
AS RANGE LEFT FOR VALUES (001, 002);

GO
CREATE PARTITION SCHEME OddEven_PartitionScheme  
AS PARTITION OddEven_PartitionFunction  
ALL TO ([PRIMARY]);  

````

**Comment by llali** [comment]
This bug is reported for DacFx 150. @kisantia  can you please see if we can repro this in DacFx 160.

**Comment by kisantia** [comment]
yes this still repros in DacFx 160. @udeeshagautam is working on a fix for it
