### ISSUE TITLE
SqlPackage.exe plus _BIN2_UTF8 collation generates invalid BACPAC

### ISSUE THREAD

**Issue by dzsquared** [microsoft/DacFx#8]
*Originally posted https://feedback.azure.com/forums/908035-sql-server/suggestions/43730865-sqlpackage-exe-plus-bin2-utf8-collation-generates*

When a database has a char column with a _BIN2_UTF8 collation, SqlPackage for Windows export generates a BACPAC file that SqlPackage .NET Core fails to import.

This problem can manifest as various error messages. The one that I have seen most often is, reformatted for clarity:

```
Exception System.FormatException: Unexpected end of stream encountered.
with Data:
    annotation_tableName=[core].[ObjectChangeType],
    DacLogContext_EntryId=bbd5810d-0795-4e0a-8a82-a34e58f1f72a
at Microsoft.Data.Tools.Schema.Sql.SqlClient.Bcp.ColumnSerializer.ReadBytes(BinaryReader reader, Int32 len, Byte[]& bytes)
in F:\B\16846\6200\Sources\Product\Source\SchemaSql\SqlClient\Bcp\ColumnSerializer.cs:line 100
The stack trace suggests a problem in BCP file (de)serialization. Indeed, there is a difference in the BCP files generated by SqlPackage for Windows vs. SqlPackage .NET Core. For a char(1) Latin1_General_100_BIN2_UTF8 column value 'X', the former tool writes bytes 02 00 58 00, while the latter tool writes just 58 00.
```

Affected Verisons:
- SqlPackage for Windows 15.0.5164.1
- SqlPackage .NET Core 15.0.5084.2

Steps to Reproduce:
- Have a local SQL Server 2019 instance.
- Install SqlPackage for Windows: https://go.microsoft.com/fwlink/?linkid=2165211
- Install SqlPackage .NET Core: choco install sqlpackage
- Run the following SQL script.
- Run the following PowerShell commands.

```SQL
CREATE DATABASE Repro COLLATE Latin1_General_100_CI_AI_SC_UTF8;
GO

USE Repro;
GO

CREATE TABLE dbo.Foo
(
    A char(1)
        COLLATE Latin1_General_100_BIN2_UTF8
        NOT NULL
        PRIMARY KEY
,
    B varchar(10)
        NOT NULL
);

INSERT dbo.Foo VALUES ('X', 'whatever');
```

```powershell
$spwin = "${env:ProgramFiles}\Microsoft SQL Server\150\DAC\bin\SqlPackage.exe"

$spcore = "${env:ChocolateyInstall}\lib\sqlpackage\tools\sqlpackage.exe"

& $spwin  /a:Export /ssn:. /sdn:Repro  /tf:repro.bacpac

& $spcore /a:Import /tsn:. /tdn:Repro2 /sf:repro.bacpac
```

**Comment by sharpjs** [comment]
I was the original author of this bug report on feedback.azure.com.

In reposting here, a key paragraph was accidentally merged into the error message example.  The paragraph is:

> **The stack trace suggests a problem in BCP file (de)serialization.** Indeed, there is a difference in the BCP files generated by SqlPackage for Windows vs. SqlPackage .NET Core. For a `char(1) Latin1_General_100_BIN2_UTF8` column value `'X'`, the former tool writes bytes `02 00 58 00`, while the latter tool writes just `58 00`.

I can confirm the incompatibility still exists in SqlPackage 15.0.5282.

I so happens that I'm trying to pick a workaround this week.

**Comment by llali** [comment]
I verified this bug doesn't happen anymore in DacFx 160. it might be a bug in SQLClient and fixed in MDS.
