### ISSUE TITLE
SDK-style project build fails with SQL files included as "None"

### ISSUE THREAD

**Issue by AndrewMcLachlan** [microsoft/DacFx#88]
- Microsoft.Build.Sql 0.1.3-preview
- .NET Framework
- Local build in Visual Studio 2022

**Steps to Reproduce:**

1. Create a SQLProj project (using the non-preview SSDT tools)
2. Include a .sql script file with a build action of Build.
3. In the script file, add two consecutive statements such as PRINT and UPDATE
4. Confirm it builds 
5. Add the <Sdk Name="Microsoft.Build.Sql" Version="0.1.3-preview" /> and remove .targets references
6. Note the build action on the SQL file is now None
7. Rebuild
8. The build log shows Error:  SQL71006: Only one statement is allowed per batch. A batch separator, such as 'GO', might be required between statements.
9. Add a GO statement
10. Rebuild
11. The build log shows Error:  SQL70001: This statement is not recognized in this context.

**Comment by JorgeCandeias** [comment]
Is that file supposed to be on the build or not, meaning is it a schema object or an extra pre/post-deployment script?

For the latter, this appears to be a quirk of the globbing behaviour of the SDK, as it includes all *.sql files in the build by default.

To go around this for now, I've added `<Build Remove />` elements in the project, for each extra file, to ignore them in the build, before the `<None Include />` elements that keep them in the project.

In the example below, the post deployment file references the extra file along the way, so I had to force remove it from the build as the SDK was building the `<None />` elements regardless. The SDK does honour the `<PostDeploy />` element properly.

```xml
<PostDeploy Include="Scripts\Script.PostDeployment.sql" />
<Build Remove="Scripts\Script.PostDeployment.Persistence.sql" />
<None Include="Scripts\Script.PostDeployment.Persistence.sql" />
```

**Comment by AndrewMcLachlan** [comment]
It is an extra script that is not part of the schema. In my test, I had one script that was to be called from the post deployment script and one that is included as a file but intended to be run on another database.

Adding <Build Remove="..." /> solved the problem for me, thanks.

**Comment by jcbeck37** [comment]
Why was this closed when the SDK still ignores the `<None>` build action and includes scripts incorrectly in the build? Is ther ean open bug for fixing this that I'm not seeing referenced here?
